### ISSUE TITLE
onion

### ISSUE THREAD

**Issue by 21f1nger** [gSpotx2f/ruantiblock_openwrt#1]
Is it possible to make a transition to onion resources

**Comment by gSpotx2f** [comment]
Implemented a long time ago (ipset -> onion), but does not work correctly with the default dnsmasq settings :)
This should help:
```
uci set dhcp.@dnsmasq[0].rebind_localhost='1'
uci set dhcp.@dnsmasq[0].rebind_domain='.onion'
uci commit
/etc/init.d/dnsmasq restart
```
