### ISSUE TITLE
Wan ip in blacklist

### ISSUE THREAD

**Issue by ASergeyV** [gSpotx2f/ruantiblock_openwrt#102]
Свой адрес попадает в список обхода. Допустим воспользуемся duckdns.org, при попытке выйти на себя же через dyndns ип адреса wan падает в черный список и как результат ничего не доступно. Список исключений при этом начинает работать только после обновления блеклиста

**Comment by boozzze** [comment]
Привет, тоже юзаю duckdns, внес с белый список, это дело одного раза же, потом проблем не возникает. Если ток сам duckdns отваливается, бывает у него на 2-5 мин

**Comment by ASergeyV** [comment]
Ну а само по себе добавление ип адреса какого либо интерфейса в список для обхода? Может это как то исключить в программе?

Можно узнать логику?

**Comment by gSpotx2f** [comment]
Косяк с duckdns.org в группировке субдоменов. В duckdns.org заблокировано много субдоменов, поэтому сработала группировка для оптимизации. [Добавил в исключения](https://github.com/gSpotx2f/ruantiblock_blacklist/blob/e3dcc14aa87e002e1d82135103b27f2c65201152/1.1/gr_excluded_sld#L16), теперь вроде должно правильно работать.

**Comment by gSpotx2f** [comment]
>Можно узнать логику?

Логика в доменах. Если домен в блэклисте, то dnsmasq, когда резолвит его в IP адрес, добавляет этот адрес в сет для обхода. Если домен из блэклиста резолвится в IP адрес интерфейса, то и получается что IP интерфейса попадает в сет.

**Comment by jvxvt** [comment]
С доменом `mooo.com` есть аналогичная проблема.

**Comment by ASergeyV** [comment]
Вот я чего и говорю: можно ли автоматически добавлять ип адреса интерфейсов в белый список?

**Comment by jvxvt** [comment]
У добавления IP адреса в белый список есть один неприятный побочный эффект - утечка памяти в nftables:
![изображение](https://github.com/user-attachments/assets/9a00d7ce-403b-4f2d-87b0-e7afaf6802cf)
