### ISSUE TITLE
Не работает должным образом

### ISSUE THREAD

**Issue by 00enterausername00** [gSpotx2f/ruantiblock_openwrt#103]
Предыдущая версия работала прекрасно. Сейчас переустановил прошивку на роутер (23.05.5) и установил новую версию антиблока. Кроме антиблока на роутере крутятся только mwan3, shadowsocks и https dns прокси. 
Единственная проблема, которая присутствует всегда - не работает обновление списков после перезагрузки, при этом ручное обновление можно запустить сразу и оно отрабатывает успешно.
Кроме этого программа часто работает непредсказуемым образом - ресурс из списка может не открываться вообще, может проксироваться, а может открываться напрямую. Было даже такое, что сайт не проксировался до тех пор, пока я его не закомментировал в пользовательском листе. Похожая ситуация была и с ресурсом, который находился в двух списках одновременно - пока не убрал из одного из них, он открывался напрямую. Я пробовал все три режима работы из веб панели и даже при работе только с пользовательским листом, состоящим из <10 строк, проблемы сохранялись.

**Comment by samara1532** [comment]
Ну проблема явно не в руантиблоке. иначе бы тут заспамили подобными сообщениями.

**Comment by gSpotx2f** [comment]
>Единственная проблема, которая присутствует всегда - не работает обновление списков после перезагрузки, при этом ручное обновление можно запустить сразу и оно отрабатывает успешно.

В плане загрузки списков не было каких-то концептуальных изменений в новой версии. Что в логе после перезагрузки? Там должны быть ошибки обновления блэклиста, когда он не может обновиться (если опция обновления при запуске включена).

>Было даже такое, что сайт не проксировался до тех пор, пока я его не закомментировал в пользовательском листе.

Если сайт закомментирован в блэклисте (т.е. фактически отсутствует там) как он может проксироваться? Не понял этот момент.

>Похожая ситуация была и с ресурсом, который находился в двух списках одновременно - пока не убрал из одного из них, он открывался напрямую.

Скорее всего в списке с более высоким приоритетом так был настроен прокси (или настроен неправильно). Каждый экземпляр записей пользователя имеет свои настройки прокси, их нужно задать для каждого экземпляра. Ещё, [здесь](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D0%B8-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F-%D0%B2-%D0%B1%D0%BB%D1%8D%D0%BA%D0%BB%D0%B8%D1%81%D1%82%D0%B5#%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B9-%D1%81-%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D0%BC%D0%B8-%D1%8D%D0%BA%D0%B7%D0%B5%D0%BC%D0%BF%D0%BB%D1%8F%D1%80%D0%B0%D0%BC%D0%B8) есть пример как протестировать работу пользовательских списков.

Также повторю, что конфигурационные файлы версии 2.x не совместимы со старыми версиями. Нужно удалить все файлы старой версии включая конфиги. Если после переустановки OpenWrt выполнялось восстановление конфигурации из бэкапа, то там могут оставаться старые конфиги и файлы ruantiblock.

**Comment by 00enterausername00** [comment]
Возможно я как-то неправильно вношу изменения в списки? Раньше команды update из консоли хватало, сейчас чтобы свежедобавленный сайт начал работать через прокси нужны толи какие-то другие манипуляции, толи нужно подождать чего-то, что работает в фоне. 

Вот сейчас добавил сайт thenorthface.com в пользовательский список. Нажал применить в вебе, там-же сделал обновление списков - ничего не изменилось (ранее добавленные работают). Интернет работает. Сделал стоп-старт службе - без изменений. Сделал дестрой, старт, апдейт - без изменений. Интернет работает.

Перезагрузил роутер. Как обычно основной лист не загрузился автоматически. Теперь перестали открываться другие сайты из листа, сайт thenorthface.com по прежнему показывает заглушку о том, что я заблокирован. Интернет работает.

Прошло несколько минут. Теперь сайт thenorthface.com перестал открываться так-же как и другие сайты из листа. Интернет работает.

Скорее всего либо по прошествии времени либо за счет моих рандомных манипуляций скоро опять все заработает, но хочется понять хотя-бы благодаря чему именно. Логи загрузки в прикрепленном файле.
[ruantiblock.log](https://github.com/user-attachments/files/17941595/ruantiblock.log)

**Comment by 00enterausername00** [comment]
>Если сайт закомментирован в блэклисте (т.е. фактически отсутствует там) как он может проксироваться? Не понял этот момент.
Я сам не понял. Либо он начал работать благодаря тому, что какой-то фоновый процесс завершился и мои предыдущие изменения вступили в силу ±одновременно c внесением новых изменений, либо при какой-то конфигурации один из листов начал выполнять функцию противоположную заданной (стал списком исключений). На роутер все ставил с нуля, без бекапов, через скрипт.

**Comment by gSpotx2f** [comment]
В логе ошибки скачивания блэклиста с гитхаба на протяжении трёх минут, т.е. нет доступа в интернет после загрузки роутера. Ruantiblock делает 3 попытки с интервалом в минуту, этого обычно достаточно. Если так долго отсутствует доступ в инет, то это не нормально. Вы писали, что на роутере mwan, т.е. сложная конфигурация с несколькими каналами или провайдерами, скорее всего какая-то проблема в конфигурации, возможно соединения с самого роутера идут через нерабочий интерфейс (т.е. приложения работающие на роутере не могут попасть в инет), это предположение. Пользовательские списки, судя по логу, загружаются нормально. Попробуйте отключить опцию `Применять правила прокси к трафику приложений роутера` в настройках ruantiblock. И покажите содержимое `/etc/config/ruantiblock`.

**Comment by 00enterausername00** [comment]
Да, ваше предположение оказалось абсолютно верным. Mwan оказывается не умеет в nftables и для нормальной работы на новых версиях openwrt ему нужно пару дополнительных пакетов, причем проблема как будто распространялась только на приложения роутера. Теперь все работает отлично.
Подскажите пожалуйста, нет ли команды, применяющей только изменения из одного листа? Хочу через тг бота управлять пользовательским списком

**Comment by gSpotx2f** [comment]
>Подскажите пожалуйста, нет ли команды, применяющей только изменения из одного листа?

Нет, все списки обновляются одной командой (`ruantiblock update`). При обновлении формируются общие для списков конфиги dnsmasq и nftables, поэтому обновление должно выполняться целиком.

**Comment by 00enterausername00** [comment]
Понял. Спасибо большое!
