### ISSUE TITLE
IPv6 Support / Поддержка IPv6

### ISSUE THREAD

**Issue by HomidWay** [gSpotx2f/ruantiblock_openwrt#104]
Is it possible to have IPv6 support in future updates? PBR does very similar things to RuAntiBlock but it has IPv6 support.

Возможна ли поддержка IPv6 в будующем? В PBR схожий механизм работы и там поддержка реализованна.

**Comment by gSpotx2f** [comment]
>Возможна ли поддержка IPv6 в будующем?

Поддержку IPv6 пока не планировал, возможно в отдалённом будущем. В реестре огромное количество записей в которых только IPv4 адреса. Ещё и списки адресов IPv6 весят больше, как сами файлы списков, так и память которую они занимают в виде данных (уже сейчас 256Мб оперативки необходимый минимум, с IPv6 будет ещё хуже). Чистого IPv6 у нас всё-равно нет, в лучшем случае параллельно с IPv4 или трансляция, т.е. получается усложнение там где можно без него обойтись.

>В PBR схожий механизм работы и там поддержка реализованна.

Принцип похожий, но назначение разное. PBR универсальный инструмент для широкого применения, для конфигураций разной сложности и назначения. Ruantiblock же предназначен для одной узкоспециализированной задачи - обход блокировок в РФ, где реальное распространение IPv6, можно сказать, ничтожно мало, а с учётом теперешних реалий врядли будет существенно повышаться в обозримом будущем.

**Comment by jvxvt** [comment]
В части поддержки IPv6 я хотел бы видеть как минимум опцию отключения DNS AAAA-записей (IPv6 адресов) для FQDN из пользовательских списков. Для этого я сейчас добавляю строку `printf "address=/%s/::\n", val >> DNSMASQ_DATA_FILE;` в подфункцию `writeDNSData` функции `ParseUserEntries` скрипта `ruantiblock`, но лучше бы эта возможность была штатной.
