### ISSUE TITLE
snapshot

### ISSUE THREAD

**Issue by samara1532** [gSpotx2f/ruantiblock_openwrt#105]
на снапе 6.6.63
некоторые приложения по старой памяти создают в темп папку dnsmasq.d
на подобие адблок-фаст
есесно работать с неё правила уже не могут.  (по дефолту у меня она стала называться, dnsmasq.cfg01411c.d )
но

руантиблок при установке начинает её использовать по умолчанию.
и тоже соответственно ничего не перенаправляется.

Кто придумал спрятать настройку переключения на кнопку "выключить" службу, дайте ему ящик пз.. пива.

но

на 2.1.0   она на этой кнопке выбирается и переключается.
на 2.1.1  она выбирается, но по итогу все-равно используется старая папка dnsmasq.d

на 2.1.0  папка указана в конфиге одна и меняется при смене настройки
на 2.1.1  прописано сразу два путя. даже если удалить не нужный, он все-равно грузит в dnsmasq.d

но, даже если на 2.1.1 это мои личные баги со сменой папки.
то использование первой по умолчанию dnsmasq.d при её наличии, явно кривая фича.

**Comment by gSpotx2f** [comment]
Вы вкусили все прелести использования нестабильной ветки snapshot ))))

В 2.1.1 было изменено имя переменной в которой определяется папка с конфигами dnsmasq. Это не должно быть проблемой если выполнять переустановку ruantiblock с полным удалением старой версии (через [скрипт uninstall](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-ruantiblock)). Судя по тому что у вас 2 переменных с папками в `/etc/config/ruantiblock` использовался старый конфиг.

>Кто придумал спрятать настройку переключения на кнопку "выключить" службу, дайте ему ящик пз.. пива.

Смысл в том, что после изменения папки dnsmasq нужно выполнить полное удаление всех файлов блэклиста (конфиги nftables и dnsmasq), поэтому изменение папки возможно только при полной очистке конфигов.

>то использование первой по умолчанию dnsmasq.d при её наличии, явно кривая фича.

Не согласен. Если папка `/tmp/dnsmasq.d` существует, значит она "привязана" к главному экземпляру dnsmasq (по умолчанию). Если её нет - используется "новая" конфигурация dnsmasq с индивидуальными папками, где путь берётся из ubus - первая папка первого экземпляра dnsmasq. Определение папки выполняется один раз (в `/etc/init.d/ruantiblock`) при первом запуске службы, потом можно переопределить с полной очисткой блэклиста. Такая схема совместима как с 23.05, так и со snapshot. Вообще, проблема в том, что эта тема с папкой конфигов dnsmasq находится в процессе обсуждения сейчас. Окончательного принятого варианта пока нет (https://github.com/openwrt/openwrt/pull/16890). Надеюсь к релизу 24.10 этот вопрос решится и будет понятно как дальше действовать.

**Comment by samara1532** [comment]
> Смысл в том, что после изменения папки dnsmasq нужно выполнить полное удаление всех файлов блэклиста (конфиги nftables и dnsmasq), поэтому изменение папки возможно только при полной очистке конфигов.

не проще её вывести наружу и подписать что нужно после смены перезапустить службу.

> Не согласен. Если папка /tmp/dnsmasq.d существует, значит она "привязана" к главному экземпляру dnsmasq (по умолчанию).

у меня она как я написал, не привязана. но руантиблок в неё двумя ногами залетает.

**Comment by gSpotx2f** [comment]
>не проще её вывести наружу и подписать что нужно после смены перезапустить службу.
или что-бы смена этой настройки, инициализировало перезапуск.

Нужно не перезапустить, а полная очистка конфигов (`ruantiblock destroy`). Вот сейчас смена папки в вебморде возможна только при выполнении полной очистки, и нужно явное подтверждение от юзера (нажать кнопку).

>у меня она как я написал, не привязана. но руантиблок в неё двумя ногами залетает.

Потому что она указана в конфиге. Папку можно переназначить. Если до релиза 24.10 примут правки, то папка `/tmp/dnsmasq.d` будет общей для всех экземпляров, я готовлюсь к этому сейчас.

>ну мог бы каждый раз)
в tmp/run всегда лежит правильный экземпляр dnsmasq

Экземпляров может быть запущено несколько, какой из них правильный? И потом, скрипт `/etc/init.d/ruantiblock` при определении папки dnsmasq записывает её в UCI, т.е. в ПЗУ, а у большинства роутеров флэш не вечный.
