### ISSUE TITLE
При перезапуске VPN интерфейса в nftables дублируются записи

### ISSUE THREAD

**Issue by jvxvt** [gSpotx2f/ruantiblock_openwrt#106]
Обнаружил небольшой баг: если перезапустить VPN интерфейс, то правила в nftables начинают дублироваться, например:
```
	chain dnsmasq_timeout_update.list1 {
		ct state new update @d.list1 { ip daddr }
		jump mark_chain.list1
		ct state new update @d.list1 { ip daddr }
		jump mark_chain.list1
		ct state new update @d.list1 { ip daddr }
		jump mark_chain.list1
	}
```

**Comment by gSpotx2f** [comment]
Спасибо! [Исправил](https://github.com/gSpotx2f/ruantiblock_openwrt/commit/2227aa2306bbff914c47110162cae7a6156ebc8e) неправильный порядок удаления цепочек nftables.
Можно не перустанавливать пакет, а скачать на роутере исправленный файл:

    wget --no-check-certificate -O /usr/bin/ruantiblock https://raw.githubusercontent.com/gSpotx2f/ruantiblock_openwrt/refs/heads/master/ruantiblock/files/usr/bin/ruantiblock

**Comment by jvxvt** [comment]
Да, баг исправлен. Cпасибо за ruantiblock!
