### ISSUE TITLE
Не работают пользовательские списки для V2 через Luci

### ISSUE THREAD

**Issue by Temerin** [gSpotx2f/ruantiblock_openwrt#107]
Сегодня после установки второй версии Ruantiblock (с предварительным удалением скриптом первой версии) заметил, что пункт "Записи пользователя" не отрабатывает.
При попытки добавления адресов через веб-интерфейс и нажатия на кнопку "Сохранить", появляется сообщение:
"Невозможно сохранить содержимое: Permission denied"
Для /etc/ruantiblock/user_lists/* всем файлам установлены права 644. При этом галочка "Включить записи пользователя" отрабатывает в интерфейсе корректно, и без неё пользовательские списки не работают вовсе, а с ней удаётся рулить путём ручного редактирования файлов

**Comment by gSpotx2f** [comment]
https://github.com/gSpotx2f/ruantiblock_openwrt/issues/100#issuecomment-2481258799

**Comment by Temerin** [comment]
Да, проблема была в кэше браузера. Благодарю. 
Добавьте, пожалуйста, эту информацию в Wiki на страницы 
"Записи пользователя в блэклисте" и "Если после установки возникли проблемы..."
