### ISSUE TITLE
Исключение обхода блокировок для айпишника внутри сети

### ISSUE THREAD

**Issue by gelato** [gSpotx2f/ruantiblock_openwrt#108]
Доброго времени суток, в первую очередь хочется поблагодарить - очень крутой проект, спасибо.
У меня такой вопрос - можно ли исключить айпишник из lan сети роутера из обхода блокировок полностью?
Вот у меня за основным роутером еще два роутера - чтоб один был с обходом, а второй ходил в сеть по-белой. Какой-то аналог "IP-адреса для режима полного прокси", только в обратную сторону...

**Comment by gSpotx2f** [comment]
Попробуйте фильтр хостов на странице настроек: `Настройки` -> `Основные настройки` -> `Фильтр хостов`. Эта опция ограничивает доступ к обходу блокировок для заданных локальных адресов.

**Comment by gelato** [comment]
Как-то и не заметил эту опцию сперва... Да, это оно, благодарю.
