### ISSUE TITLE
В свежих снапшотах  APK вместо OPKG

### ISSUE THREAD

**Issue by Lem4ek** [gSpotx2f/ruantiblock_openwrt#109]
В новых версиях APK вместо OPKG необходимо внести изменения в скрипт и инструкцию.

**Comment by gSpotx2f** [comment]
Недавно уже обсуждали про APK: https://github.com/gSpotx2f/ruantiblock_openwrt/issues/101#issuecomment-2486365826 и https://github.com/gSpotx2f/ruantiblock_openwrt/issues/101#issuecomment-2506586413

**Comment by Lem4ek** [comment]
Поставил, но почему-то не видит мои amneziawg-VPN интерфейсы
