### ISSUE TITLE
Полная проксификация всего трафика, без фильтрации блэклиста

### ISSUE THREAD

**Issue by loons1k** [gSpotx2f/ruantiblock_openwrt#11]
Добрый день. Можно ли использовать переменную в openwrt конфиге ruantiblock DEF_TOTAL_PROXY=1, но при этом udp траффик отправлять напрямую через провайдера без проксификации, а так же использовать белый список для исключений правил для некоторых ip адресов в локальной сети?

**Comment by gSpotx2f** [comment]
Режим "total proxy" когда-то присутствовал в старых версиях, но давно уже выпилен, ибо приводил к "сюрпризам" в некоторых конфигурациях... Если вам не нужен обход блокировок по реестру, то вместо ruantiblock попробуйте [vpn-policy-routing](https://openwrt.org/packages/pkgdata/vpn-policy-routing).
