### ISSUE TITLE
3 level domains cause dns crash

### ISSUE THREAD

**Issue by Bazo0Z0o** [gSpotx2f/ruantiblock_openwrt#12]
Добрый день.
Обнаружил странный баг.
решал вопрос доступа к themoviedb.org. Там редирект на www.themoviedb.org.
При добавлении www.themoviedb.org в записи пользователей перестает работать DNS на роутере впринципе.
Подумал что я наверное не оень умный и поменял на api.themoviedb.org.
Эффект тот же - все устройства в сети перестают резолвить интернет.
Резюмируя:
OpenWRT, настроено для работы только с записями пользователя, tor. Работает все отлично пока не добавишь домены 3 уровня в записи пользователя.

**Comment by gSpotx2f** [comment]
Похоже проблема на стороне домена `themoviedb.org`. DNS настроен неправильно (или их взломали)... `www.themoviedb.org` и `api.themoviedb.org` резолвятся в `127.0.0.1`, что и приводит к глюкам. При проблемах с DNS сначала проверяйте во что у вас резолвится домен (nslookup в помощь).

**Comment by Bazo0Z0o** [comment]
Добрый день.
Вчера разобрался: они как то сделали сплит и для тех кто в России
резолвится в 127.0.0.1. Если указать 9.9.9.9 в качестве днс для этого
домена-работает, правда хз чей это днс. В любом случае, если один домен
резолвится в 127.0.0.1, почему перестает резолвится весь остальной
интернет?... В общем можно добавить в FAQ если он у вас есть:-).  Спасибо,
хорошего дня!


чт, 17 нояб. 2022 г., 23:48 gSpotx2f ***@***.***>:

**Comment by vit9696** [comment]
Как я понимаю, themoviedb.org блокирует доступ на своей стороне, а не со стороны РКН. Хотелось бы такие сайты добавлять не вручную, а посредством подключения списка, пополняемого совместными усилиями. Я создал тикет в https://github.com/gSpotx2f/ruantiblock_blacklist/issues/2, но возможно в этом репозитории они не мониторятся.

**Comment by Bazo0Z0o** [comment]
Так и и есть, спасибо за тикет!

пт, 18 нояб. 2022 г., 10:37 Vitaly Cheptsov ***@***.***>:

**Comment by gSpotx2f** [comment]
@Bazo0Z0o
>В любом случае, если один домен резолвится в 127.0.0.1, почему перестает резолвится весь остальной
интернет?

Эта команда должна решить проблему:

    uci set dhcp.@dnsmasq[0].rebind_localhost='0'
