### ISSUE TITLE
Ошибка ruantiblock: Module run attempt 1: failed [/usr/libexec/ruantiblock/ruab_parser.lua]

### ISSUE THREAD

**Issue by hulitolku** [gSpotx2f/ruantiblock_openwrt#13]
В логах красным отмечена ошибка **ruantiblock: Module run attempt 1: failed [/usr/libexec/ruantiblock/ruab_parser.lua]**
Куда копать?

А также, после установки пайтон-модуля, при **/usr/bin/ruantiblock update** в логах ошибка **ruantiblock: Module run attempt 1: failed [/usr/libexec/ruantiblock/ruab_parser.py]**

**Comment by gSpotx2f** [comment]
Блэклист обновляется? Обход блокировок работает? Когда появляется это сообщение: после загрузки роутера или постоянно при обновлении через cron? Давайте больше информации о проблеме.

**Comment by hulitolku** [comment]
Установщик пайтон-парсера для 19.07, почему то не записывал файл ruab_parser.py в роутер.
Пришлось вручную заливать.
Все работает теперь.

**Comment by koroleves** [comment]
> Установщик пайтон-парсера для 19.07, почему то не записывал файл ruab_parser.py в роутер. Пришлось вручную заливать. Все работает теперь.

А как это сделать? напишите по-шагам, пожалуйста (похожа ошибка у меня)
