### ISSUE TITLE
Не хватает памяти.

### ISSUE THREAD

**Issue by hulitolku** [gSpotx2f/ruantiblock_openwrt#15]
Openwrt 19.07 Mikrotik rb951ui-2hnd 
Памяти на борту:
![image](https://user-images.githubusercontent.com/30010365/204083370-53a6f4ea-08e3-4b9a-a480-0ecaf8e79ca3.png)
 Примонтировал флешку 4гб:
 
![image](https://user-images.githubusercontent.com/30010365/204083439-087230cc-054c-4896-b472-5f5d3b6204ed.png)

Но в логах все равно выдало:  **/usr/bin/lua: not enough memory** и служба отключилась Ruantiblock
Что я делаю не так?

**Comment by gSpotx2f** [comment]
Очевидно, нехватает оперативной памяти для хранения списка блокировок. Вы перенесли конфиги (текстовые файлы) на флэшку, но данные из этих конфигов загружаются в оперативную память. Чтобы ipset и dnsmasq могли работать со списками доменов и ip-адресов, они должны держать их в памяти. На скриншоте свободной памяти всего 18Мб! из 128. У вашего роутера недостаточно оп.памяти для полного списка блокировок. Попробуйте конфигурацию с минимальным списком - в [wiki](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%95%D1%81%D0%BB%D0%B8-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B8-%D0%B2%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BB%D0%B8-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B...) об этом написано (п.8).

**Comment by hulitolku** [comment]
А примонитрованный SWAP раздел на флешке не решит проблему?

**Comment by gSpotx2f** [comment]
Очень мало свободной оперативной памяти. На роутере выполняются какие-нибудь дополнительные сервисы (торрент-клиент, ad-block, медиасервер и пр.)?

**Comment by hulitolku** [comment]
Нет. 
Только Wireguard-сервер, ruantiblock с тором и dnnscypt-proxy2.

**Comment by gSpotx2f** [comment]
Вообще, tor тоже память отжирает (особенно если установлен tor-geoip). Память на скриншоте при запущенном ruantiblock или так всегда? Короче, пробуйте конфигурацию с минимальным списком:

    uci set ruantiblock.config.ipset_clear_sets="1"
    uci set ruantiblock.config.bllist_preset="antifilter-ip"
    uci set ruantiblock.config.bllist_ip_limit="0"
    uci set ruantiblock.config.bllist_summarize_ip="0"
    uci set ruantiblock.config.bllist_summarize_cidr="0"
    uci commit ruantiblock

если даже так не хватает памяти - то тут ничем не помочь. Только роутер с RAM >=256Мб... SWAP в данном случае не поможет. SWAP полезен для редко используемых данных занимающих память, здесь же списки блокировок используются постоянно, для каждого DNS-запроса или ip пакета. В wiki упоминается про swap в контексте работы парсера (lua или python) при обновлении, который в момент обработки реестра хранит промежуточные данные в памяти. Объективно, сейчас девайс с RAM 128Мб уже вряд ли справится с обработкой полного реестра.
