### ISSUE TITLE
Заблокированные сайты не загружаются

### ISSUE THREAD

**Issue by 4namus** [gSpotx2f/ruantiblock_openwrt#16]
Настроил на OpenWRT 22.03.2 по инструкции через Tor,  https-dns-proxy тоже настроил по инструкции отсюда, ошибок никаких не выдает, но при переходе на заблокированные сайты ничего не происходит, и заглушка Ростелекома не вылазит, и страницу нужную не грузит. Остальные сайты работают как раньше. Такое ощущение, что Tor не работает. Не знаю может причина быть в том, что мой роутер Xiaomi Mi R3G, получает интернет по  WAN интерфейсу от Ростелекомовского оптического роутера. Как можно найти концы проблемы?

**Comment by gSpotx2f** [comment]
Сам по себе Tor у вас работает, без ruantiblock? На ПК, например...

**Comment by 4namus** [comment]
> 

На ПК тоже не работает, пробовал и на Ростелекоме, и интернет раздавал с телефона, оператор Теле2

**Comment by gSpotx2f** [comment]
Похоже, провайдеры блокируют Tor. Нужна настройка с использованием [мостов](https://bridges.torproject.org/).
