### ISSUE TITLE
Module ruab_parser.lua run failed on ruantiblock update"

### ISSUE THREAD

**Issue by Bazo0Z0o** [gSpotx2f/ruantiblock_openwrt#2]
Hello!
When i trying to "ruantiblock update" - i always get " Module run attempt: failed".
I tryed to remove/install and no effect(.

root@Bazoozoo:~# /usr/bin/ruantiblock update
 ruantiblock update...
Killed
 Module run attempt 1: failed [/usr/libexec/ruantiblock/ruab_parser.lua]
Killed
 Module run attempt 2: failed [/usr/libexec/ruantiblock/ruab_parser.lua]
Killed
 Module run attempt 3: failed [/usr/libexec/ruantiblock/ruab_parser.lua]
 Module error! [/usr/libexec/ruantiblock/ruab_parser.lua]
udhcpc: started, v1.33.2
udhcpc: sending discover
udhcpc: no lease, failing

**Comment by gSpotx2f** [comment]
Looks like a lack of RAM... You need at least 256 MB of RAM at the moment.
To optimize RAM usage, try the following settings:

	uci set ruantiblock.config.bllist_source="rublacklist"
	uci set ruantiblock.config.ipset_clear_sets="1"
	uci commit ruantiblock

You can also read: [Lack of RAM (paragraph 8)](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%95%D1%81%D0%BB%D0%B8-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B8-%D0%B2%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BB%D0%B8-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B...), [Blacklist optimization](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%A1%D0%BF%D0%BE%D1%81%D0%BE%D0%B1%D1%8B-%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8-%D0%B8-%D1%81%D0%BE%D0%BA%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BA%D0%BE%D0%BB%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B0-%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B5%D0%B9-%D0%B2-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B5-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BE%D0%BA).

**Comment by spvkgn** [comment]
То же самое. Судя по системлогу, при запуске ruantiblock `dnsmasq` не находит `ruantiblock.conf` и далее уже ничего не резолвится. В моем случае включена RAM-конфигурация (256 RAM), установлен https-dns-proxy.
```
Sat Apr  9 13:32:05 2022 user.info ruantiblock: start...
Sat Apr  9 13:32:05 2022 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
Sat Apr  9 13:32:10 2022 daemon.crit dnsmasq[1]: cannot access /tmp/dnsmasq.d/ruantiblock.conf: No such file or directory
Sat Apr  9 13:32:10 2022 daemon.crit dnsmasq[1]: FAILED to start up
Sat Apr  9 13:32:15 2022 daemon.crit dnsmasq[1]: cannot access /tmp/dnsmasq.d/ruantiblock.conf: No such file or directory
Sat Apr  9 13:32:15 2022 daemon.crit dnsmasq[1]: FAILED to start up
Sat Apr  9 13:32:20 2022 daemon.crit dnsmasq[1]: cannot access /tmp/dnsmasq.d/ruantiblock.conf: No such file or directory
Sat Apr  9 13:32:20 2022 daemon.crit dnsmasq[1]: FAILED to start up
Sat Apr  9 13:32:25 2022 daemon.crit dnsmasq[1]: cannot access /tmp/dnsmasq.d/ruantiblock.conf: No such file or directory
Sat Apr  9 13:32:25 2022 daemon.crit dnsmasq[1]: FAILED to start up
Sat Apr  9 13:32:30 2022 daemon.crit dnsmasq[1]: cannot access /tmp/dnsmasq.d/ruantiblock.conf: No such file or directory
Sat Apr  9 13:32:30 2022 daemon.crit dnsmasq[1]: FAILED to start up
Sat Apr  9 13:32:35 2022 daemon.crit dnsmasq[1]: cannot access /tmp/dnsmasq.d/ruantiblock.conf: No such file or directory
Sat Apr  9 13:32:35 2022 daemon.crit dnsmasq[1]: FAILED to start up
Sat Apr  9 13:32:35 2022 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
```
Пользовался ранее прежней версией на Падаване, там всё работало.

**Comment by gSpotx2f** [comment]
@spvkgn, у вас есть те же сообщения об ошибке модуля при обновлении, что и у @Bazo0Z0o?

**Comment by Bazo0Z0o** [comment]
Добрый день.
Наконец удалось выкроить время - проверить.
Не помогает(((((:
```
root@gate:~# uci set ruantiblock.config.bllist_source="rublacklist"
root@gate:~# uci set ruantiblock.config.ipset_clear_sets="1"
root@gate:~# uci commit ruantiblock
root@gate:~# /usr/bin/ruantiblock update
 ruantiblock update...
Killed
 Module run attempt 1: failed [/usr/libexec/ruantiblock/ruab_parser.lua]
Killed
 Module run attempt 2: failed [/usr/libexec/ruantiblock/ruab_parser.lua]
Killed
 Module run attempt 3: failed [/usr/libexec/ruantiblock/ruab_parser.lua]
 Module error! [/usr/libexec/ruantiblock/ruab_parser.lua]
 Filling ipsets...
 Ok
udhcpc: started, v1.33.2
udhcpc: sending discover
udhcpc: no lease, failing
```
Памяти 128 Мб, Железяка: Xiaomi Redmi Router AC2100

**Comment by gSpotx2f** [comment]
@Bazo0Z0o, попробуйте самую лёгкую конфигурацию:

	uci set ruantiblock.config.bllist_mode="ip"
	uci set ruantiblock.config.ipset_clear_sets="1"
	uci set ruantiblock.config.bllist_source="antifilter"
	uci commit ruantiblock

**Comment by Bazo0Z0o** [comment]
Увы - не помогает:
```
root@gate:~# uci set ruantiblock.config.bllist_mode="ip"
root@gate:~# uci set ruantiblock.config.ipset_clear_sets="1"
root@gate:~# uci set ruantiblock.config.bllist_source="antifilter"
root@gate:~# uci commit ruantiblock
root@gate:~# /usr/bin/ruantiblock update
 ruantiblock update...
 Received entries: IP: 0, CIDR: 9941, FQDN: 0
 Blacklist updated
 Filling ipsets...
 Ok
udhcpc: started, v1.33.2
udhcpc: sending discover
udhcpc: no lease, failing
```

**Comment by 335maria335** [comment]
Здравствуйте. При загрузке роутера ошибка, хотя всё работает. Потом уже без ошибки обновляет . Память 250Мб. owrt 22.03.0
<a href="https://yapx.ru/v/T6egK" title="Изображение загружено на фотохостинг yapx.ru"><img src="https://i.yapx.ru/T6egK.png" alt="Хостинг картинок yapx.ru"></a>

**Comment by gSpotx2f** [comment]
@335maria335, парсер отрабатывает со второй попытки. Если ошибка при загрузке роутера, то может быть интернет ещё недоступен в момент начала обновления блэклиста (или DNS и т.п.)
