### ISSUE TITLE
Не создается директория /usr/libexec/ruantiblock

### ISSUE THREAD

**Issue by Vyacheslav-S** [gSpotx2f/ruantiblock_openwrt#20]
При ручной установке ruantiblock  без дополнений (ruantiblock-mod-lua/ruantiblock-mod-py) не создается директория /usr/libexec/ruantiblock и соответственно не работает вкладка web интерфикса  Ruantiblock - Settings.
`mkdir /usr/libexec/ruantiblock `решает проблему.
Возможно эта проблема  появилась в новой версии v0.9.6.

**Comment by gSpotx2f** [comment]
Если не установлен модуль блэклиста, то папка `/usr/libexec/ruantiblock` не нужна. В этом случае, в веб-интерфейсе, на странице `Settings` отсутствует вкладка с настройками модуля. Если у вас на странице `Settings` выскакивает ошибка, то это может быть связано с обновлением файла `settings.js` в последней версии (я намекаю на кэш браузера и т.п., если вы обновляли ruantiblock с предыдущих версий).
