### ISSUE TITLE
Не лаботает лог

### ISSUE THREAD

**Issue by 335maria335** [gSpotx2f/ruantiblock_openwrt#21]
После обновления не работает лог.
Вот что пишет : Невозможно загрузить данные лога: Access to command denied by ACL
Всё работает. Не нашёл как удалить сообщение.

**Comment by labastov** [comment]
аналогичная проблема.

**Comment by gSpotx2f** [comment]
@labastov, был баг с правами доступа, уже исправлен [несколько недель назад](https://github.com/gSpotx2f/ruantiblock_openwrt/commit/574fa6c4d42c978898e6fe2bf95d53dd79ef5aa8).
Можете просто скачать файл из репозитория на роутер, чтобы не переустанавливать всё заново:

    wget --no-check-certificate -O /usr/share/rpcd/acl.d/luci-app-ruantiblock.json https://raw.githubusercontent.com/gSpotx2f/ruantiblock_openwrt/master/luci-app-ruantiblock/root/usr/share/rpcd/acl.d/luci-app-ruantiblock.json
    /etc/init.d/rpcd restart
