### ISSUE TITLE
AX6 Redmi не работает обход блокировки OpenWrt SNAPSHOT r22001

### ISSUE THREAD

**Issue by AceWeal** [gSpotx2f/ruantiblock_openwrt#22]
При обновлении списка фдгн пишет
/tmp/ruantiblock/ruantiblock.ip:2:5-5: Error: Could not process rule: File exists
set i {type ipv4_addr;size 1000000;policy memory;elements={172.67.169.217,52.95.156.5,94.242.234.78,104.21.27.67,172.67.150.171,104.21.80.144,104.24.125.57,23.3.90.96,94.242.232.82,104.28.29.47,143.204.98.73,104.27.170.65,34.243.64.104,172.67.216.96,104.21.54.49,13.32.168.29,104.27.149.58,172.67.165.82,35.186.178.49,23.111.80.177,104.21.21.162,104.18.60.212,104.21.77.27,104.21.9.121,5.9.7.183,104.21.5.227,185.82.210.89,172.67.198.54,172.67.130.90,52.57.233.15,172.67.128.16,104.31.86.24,35.185.254.89,2.19.205.10,104.21.9.192,91.132.151.192,68.183.4.179,13.225.84.47,185.53.177.53,104.31.69.159,104.17.80.57,164.138.29.136,13.32.123.61,104.21.35.14,143.204.245.25,104.27.138.13,172.67.180.33,149.202.139.252,184.173.145.249,163.44.167.54,3.248.16.180,104.16.81.41,104.21.37.87,104.21.84.6,104.21.57.182,104.27.188.35,52.211.212.239,172.67.182.142,104.18.46.231,172.67.207.129,13.35.183.115,104.16.138.250,104.21.48.199,104.21.96.41,172.67.208.84,52.85.238.87,212.110.135.71,172.67.185.98,104.21.27.22,172.67.153.80,52.2
    ^
 Error! Nft set wasn't updated

**Comment by anomalyQC** [comment]
Подтверждаю. Роутер другой.

- `/tmp/ruantiblock/ruantiblock.ip:2:5-5: Error: Could not process rule: File exists
set i {type ipv4_addr;size 1000000;policy memory;elements={172.67.169.217,52.95.156.5,94.242.234.78,104.21.27.67,172.67.150.171,104.21.80.144,104.24.125.57,23.3.90.96,94.242.232.82,104.28.29.47,143.204.98.73,104.27.170.65,34.243.64.104,172.67.216.96,104.21.54.49,13.32.168.29,104.27.149.58,172.67.165.82,35.186.178.49,23.111.80.177,104.21.21.162,104.18.60.212,104.21.77.27,104.21.9.121,5.9.7.183,104.21.5.227,185.82.210.89,172.67.198.54,172.67.130.90,52.57.233.15,172.67.128.16,104.31.86.24,35.185.254.89,2.19.205.10,104.21.9.192,91.132.151.192,68.183.4.179,13.225.84.47,185.53.177.53,104.31.69.159,104.17.80.57,164.138.29.136,13.32.123.61,104.21.35.14,143.204.245.25,104.27.138.13,172.67.180.33,149.202.139.252,184.173.145.249,163.44.167.54,3.248.16.180,104.16.81.41,104.21.37.87,104.21.84.6,104.21.57.182,104.27.188.35,52.211.212.239,172.67.182.142,104.18.46.231,172.67.207.129,13.35.183.115,104.16.138.250,104.21.48.199,104.21.96.41,172.67.208.84,52.85.238.87,212.110.135.71,172.67.185.98,104.21.27.22,172.67.153.80,52.2
    ^
 Error! Nft set wasn't updated
`

Так же не работает настройка "Update at startup", приходиться обновлять вручную.
Версия 1.0, r22000-6bc675c0be

**Comment by gSpotx2f** [comment]
В OpenWrt что-то поломали в nftables в последних коммитах. Восстановление конфигурации (`nft -f`) работает некорректно. У меня snapshot, где-то трёхнедельной давности, работает правильно. Напомню, что версии snapshot предназначены для разработчиков и являются нестабильными.

**Comment by gSpotx2f** [comment]
Похоже, нашёл решение проблемы...
Сначала полностью выключите ruantiblock и удалите всё из папки /tmp/ruantiblock:

    /usr/bin/ruantiblock destroy
    rm /tmp/ruantiblock/*

Перекачайте 2 файла из репо:

    wget --no-check-certificate -O /etc/ruantiblock/ruantiblock.conf https://raw.githubusercontent.com/gSpotx2f/ruantiblock_openwrt/master/ruantiblock/files/etc/ruantiblock/ruantiblock.conf
    wget --no-check-certificate -O /usr/bin/ruantiblock https://raw.githubusercontent.com/gSpotx2f/ruantiblock_openwrt/master/ruantiblock/files/usr/bin/ruantiblock

Потом включите и обновите блэклист:

    /usr/bin/ruantiblock start
    /usr/bin/ruantiblock update

**Comment by AceWeal** [comment]
Работает теперь
