### ISSUE TITLE
ruantiblock-mod-py

### ISSUE THREAD

**Issue by Lem4ek** [gSpotx2f/ruantiblock_openwrt#24]
Нерабочая ссылка для Snapshot: 404: Not Found

Downloading 'https://raw.githubusercontent.com/gSpotx2f/packages-openwrt/master/snapshot/ruantiblock-mod-py_1.0-0_all.ipk'
Connecting to 185.199.111.133:443
HTTP error 404

**Comment by gSpotx2f** [comment]
Исправил. Правильная ссылка: [https://raw.githubusercontent.com/gSpotx2f/packages-openwrt/master/snapshot/ruantiblock-mod-py_1.1-0_all.ipk](https://raw.githubusercontent.com/gSpotx2f/packages-openwrt/master/snapshot/ruantiblock-mod-py_1.1-0_all.ipk).
