### ISSUE TITLE
Не хватает Whitelist

### ISSUE THREAD

**Issue by zalessky** [gSpotx2f/ruantiblock_openwrt#25]
Есть пользовательский блэклист, очень удобен и самодостаточен. Нужен аналогичный вайтлист для записей, которые присутствуют в блеклистах, но все равно должны ходить напрямую через обычное соединение - не через обход. И по аналогии с блэклистом - с возможностью выбора DNS

Пример: https://rezka.ag/ - через VPN открывается, но воспроизводить не хочет, т.к. "К сожалению, это видео не доступно в вашем регионе"
Просто перебором IP/CIDR, как в фильтре хостов, не справиться, т.к. многие прячутся за Cloudflare

**Comment by ilyasyakubov** [comment]
Зашел сюда, чтобы попросить разработчика добавить whitelist!
Не пускает на питерские Госуслуги и еще некоторые сайта.
Очень нужна возможность добавлять сайты в список исключений!

**Comment by zalessky** [comment]
> Он уже есть: [модуль-парсер](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/Lua%E2%80%91%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C) + [fqdn_filter и ip_filter](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B5%D0%B9-%D0%B1%D0%BB%D1%8D%D0%BA%D0%BB%D0%B8%D1%81%D1%82%D0%B0-%D0%BF%D0%BE-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0%D0%BC).

В интерфейсе luci-app раньше были, если мне память не изменяет. Теперь нет

**Comment by gSpotx2f** [comment]
@zalessky, нужно установить модуль-парсер и тогда вкладка с его настройками будет отображаться в веб-интерфейсе.

**Comment by ilyasyakubov** [comment]
> Он уже есть: [модуль-парсер](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/Lua%E2%80%91%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C) + [fqdn_filter и ip_filter](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B5%D0%B9-%D0%B1%D0%BB%D1%8D%D0%BA%D0%BB%D0%B8%D1%81%D1%82%D0%B0-%D0%BF%D0%BE-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0%D0%BC).

Спасибо, помогло! Простите за невнимательность!

**Comment by ilyasyakubov** [comment]
> @gSpotx2f Спасибо, помогло! Простите за невнимательность!

@gSpotx2f нет, не помогло. Я включил FQDN-filter и прописал в нем `gu[.]spb[.]ru` но сайт все равно не открывается!

**Comment by gSpotx2f** [comment]
@ilyasyakubov, в домене `spb.ru` много заблокированных сайтов и он попал под группировку в парсере, потому что не внесён в список доменов не подлежащих оптимизации (BLLIST_GR_EXCLUDED_SLD), т.е. все поддомены `spb.ru` заворачиваются в VPN. Видимо, госуслуги пускают только из РФ. Я добавил `spb.ru` [в список исключений](https://github.com/gSpotx2f/ruantiblock_blacklist/blob/1b1fd151250404c797ea45e7d562930146818bb3/1.1/ruantiblock_fqdn.conf#L48). Верните режим обновления блэклиста `ruantiblock-fqdn` и обновите блэклист.

>Blacklist module: ruab_parser.py
Blacklist update mode: ruantiblock - fqdn

Кстати, режим `ruantiblock-fqdn` (как и `ruantiblock-ip`) вообще не использует модуль блэклиста, в этом режиме загружаются уже готовые конфиги из [моего репозитория с блэклистом](https://github.com/gSpotx2f/ruantiblock_blacklist), т.е. ваш роутер не выполняет никакой работы с реестром, а просто скачивает готовые файлы. Для работы модуля нужно выбрать режим обновления использующий модуль (эти режимы помечены `*` в веб-интерфейсе), например, `zapret-info-fqdn`.

**Comment by zalessky** [comment]
> нужно установить модуль-парсер и тогда вкладка с его настройками будет отображаться в веб-интерфейсе.

да, спасибо, получилось

**Comment by ilyasyakubov** [comment]
> Я добавил `spb.ru` [в список исключений](https://github.com/gSpotx2f/ruantiblock_blacklist/blob/1b1fd151250404c797ea45e7d562930146818bb3/1.1/ruantiblock_fqdn.conf#L48). Верните режим обновления блэклиста `ruantiblock-fqdn` и обновите блэклист.

@gSpotx2f спасибо! Теперь сайт работает!
