### ISSUE TITLE
luci-i18n-ruantiblock-ru_1.1 не ставится

### ISSUE THREAD

**Issue by zalessky** [gSpotx2f/ruantiblock_openwrt#26]
`root@OpenWrt:~# opkg install /tmp/luci-i18n-ruantiblock-ru_1.1-0_all.ipk
Unknown package 'luci-i18n-ruantiblock-ru'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-i18n-ruantiblock-ru
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-i18n-ruantiblock-ru found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-i18n-ruantiblock-ru.
`

**Comment by gSpotx2f** [comment]
Вы обновили список доступных пакетов (`opkg update`) перед установкой `luci-i18n-ruantiblock-ru_1.1-0_all.ipk`?

**Comment by zalessky** [comment]
все делал, как написано в инструкции: https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-v1.1

сейчас уже не проверю, как будет себя вести, если обновить список пакетов: откатился на автоматический скрипт.
