### ISSUE TITLE
Две проблемы.

### ISSUE THREAD

**Issue by Lem4ek** [gSpotx2f/ruantiblock_openwrt#29]
Добрый день. Спасибо большое за старания. Но столкнулся с двумя проблемами.
1. Добавил в записи пользователя сайт 'Agar.io', но он думает все-равно, что я из Рф "The owner of this website (agar.io) has banned the country or region your IP address is in (RU) from accessing this website."
2. При подключение к duckdns, пропадает интернет полностью(отключаю руантиблок и все работает). IP статичный

Может подскажешь, как это решить?

**Comment by gSpotx2f** [comment]
>Добавил в записи пользователя сайт 'Agar.io', но он думает все-равно, что я из Рф "The owner of this website (agar.io) has banned the country or region your IP address is in (RU) from accessing this website."

Не подтверждаю. При добавлении в "записи пользователя" сайт доступен (там какие-то игры или типа того). Напрямую, действительно, стоит региональный лок. Для включения "записей пользователя" нужно включить саму опцию добавления записей (чекбокс "Включить" в веб морде):

    uci set ruantiblock.config.add_user_entries="1"
    uci commit

Добавить домен в "Записи пользователя":

    echo "agar.io" >> /etc/ruantiblock/user_entries

Выполнить обновление блэклиста:

    /usr/bin/ruantiblock update

Далее, если вы недавно пытались зайти на этот сайт, нужно очистить кэш DNS (в Windows: `ipconfig /flushdns`), и также на роутере перезапустить dnsmasq `/etc/init.d/dnsmasq restart`, чтобы он тоже очистил кэш.

>При подключение к duckdns, пропадает интернет полностью(отключаю руантиблок и все работает). IP статичный

Про DDNS на роутере я вообще не в курсе... Видимо, какая-то несовместимость настроек DNS. Ruantiblock в режиме `fqdn` использует DNS (dnsmasq) для обхода блокировок. Надо либо разбираться подробно с настройками DNS (лучший вариант), либо попробовать переключить ruantiblock в режим `ip`:

    uci set ruantiblock.config.bllist_preset="ruantiblock-ip"
    uci commit
    /usr/bin/ruantiblock update

Но учтите, что в режиме `ip` есть вероятность, что некоторые не заблокированные сайты, также, будут заворачиваться в VPN или Tor.

**Comment by id259** [comment]
> 2\. При подключение к duckdns, пропадает интернет полностью(отключаю руантиблок и все работает). IP статичный\

Подтверждаю, если запустить ddns совестно с ruantiblock интернет отваливается через пару минут.

> либо попробовать переключить ruantiblock в режим `ip`:

После переключения ruantiblock в ip отвала интернета не наблюдается.

**Comment by AJleKcAHgP68** [comment]
Кстати о DNS, на днях пытался поставить в качестве dns сервера adguard и яндекс
По итогу у меняч или не рабооал обход блокировок или вообще пропадал интернет
