### ISSUE TITLE
Gosuslugi и  Авито не работают.

### ISSUE THREAD

**Issue by koroleves** [gSpotx2f/ruantiblock_openwrt#3]
После запуска появилась реклама в ютьюбе, перестали работать авито, gosuslugi, pgu.mos.ru. Они жалуются на угрозу безопасности.  какубю сторону копать?

**Comment by gSpotx2f** [comment]
Попробуйте такую конфигурацию:

	uci set ruantiblock.config.bllist_mode="fqdn"
	uci set ruantiblock.config.ipset_clear_sets="1"
	uci set ruantiblock.config.bllist_source="rublacklist"
	uci set ruantiblock.config.ip_limit="0"
	uci set ruantiblock.config.fqdn_filter="1"
	uci set ruantiblock.config.summarize_ip="1"
	uci set ruantiblock.config.summarize_cidr="1"
	uci commit ruantiblock
	/usr/bin/ruantiblock update

**Comment by koroleves** [comment]
Спасибо! Вам огромное за комментарий! Пока не получается настроить, кажется WAN и TUN интерфейсы "конкурируют" друг с другом. Тунель пытался создать по этой инструкции. https://github.com/StreisandEffect/streisand/wiki/Setting-an-OpenWrt-Based-Router-as-OpenVPN-Client Она правильная?

**Comment by gSpotx2f** [comment]
Посмотрите раздел про OpenVPN в официальном wiki OpenWrt: [https://openwrt.org/docs/guide-user/services/vpn/openvpn/start](https://openwrt.org/docs/guide-user/services/vpn/openvpn/start)...
