### ISSUE TITLE
Как правильно добавить свои сайты?

### ISSUE THREAD

**Issue by 5k1n** [gSpotx2f/ruantiblock_openwrt#30]
Добрый день, спасибо за отличное расширение и быструю понятную установку и крутым FAQ! 

1) Есть пара сайтов которыми пользуюсь, и им недостаточно добавить просто домен в список для корректной работы
Подозреваю там какие-то сложные редиректы

tickmill.com
proton.me / protonmail.com

2)  еще картинки в инсте не грузятся

подскажите, как найти все необходимое для пользовательского списка, чтобы такого плана сайты стали корректно работать через WG ?

**Comment by 5k1n** [comment]
попробовал найти все адреса причастные к сайту... 
https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=EXCLUDE&q=tickmill.com&cursor=eyJ2ZXJzaW9uIjoxLCJzb3J0IjpbeyJfc2NvcmUiOnsib3JkZXIiOiJkZXNjIn19LHsiaXAiOnsib3JkZXIiOiJhc2MiLCJtb2RlIjoibWluIiwibWlzc2luZyI6Il9sYXN0In19LHsibmFtZS5fX3JhdyI6eyJvcmRlciI6ImFzYyIsIm1vZGUiOiJtaW4iLCJtaXNzaW5nIjoiX2xhc3QifX1dLCJzZWFyY2hfYWZ0ZXIiOlsyMy40OTIzODYsIjE4LjE5NC42MC4xOTMiLG51bGxdLCJyZXZlcnNlZCI6ZmFsc2V9

не помогло

также добавил все домены компании tickmill - не помогло

**Comment by gSpotx2f** [comment]
Какая у вас конфигурация ruantiblock, какой список блокировок (свой или полный РКН)?

>tickmill.com

tickmill.com, похоже, на своей стороне что-то намутили. Там циклический редирект на tickmill.eu и обратно. tickmill.com есть в реесте, tickmill.eu - нет. Добавьте `tickmill.eu` в "записи пользователя" (желательно с очисткой DNS кэша, как описано [тут](https://github.com/gSpotx2f/ruantiblock_openwrt/issues/29#issuecomment-1555901390)), после этого у меня нормально отрабатывает редирект и сайт доступен.

>proton.me / protonmail.com

proton.me, protonmail.com - сейчас проверил, доступны без дополнительных телодвижений в стандартной конфигурации блэклиста `ruantiblock-fqdn`. С изображениями в инстграмм, также, у себя проблем не вижу.

>подскажите, как найти все необходимое для пользовательского списка, чтобы такого плана сайты стали корректно работать через WG ?

Не понял вопроса... Пользовательский список - это доп. опция к реестру. Те кому необходимы свои дополнительные записи - добавляют их. Например, я его вообще не использую, мне достаточно стандартной конфигурации `ruantiblock-fqdn`. Если какие-то сайты, со своей стороны, блочат трафик из вашего региона, то тут нужно в ручном режиме добавлять их в "записи пользователя", готового полного списка таких сайтов я не знаю (вот [тут](https://github.com/gSpotx2f/ruantiblock_openwrt/issues/12#issuecomment-1321290354) кто-то пытается составлять такой список).

**Comment by 5k1n** [comment]
> proton.me, protonmail.com - сейчас проверил, доступны без дополнительных телодвижений в стандартной конфигурации блэклиста `ruantiblock-fqdn`. С изображениями в инстграмм, также, у себя проблем не вижу.

у меня почему - то настройка с fdqn вообще не работает, у меня ip , дело в https dns proxy ? работает исправно с ip

не нашёл, кстати, в чем разница принципиальная двух вариантов (fqdn / ip) , какой вариант лучше/быстрее ?



> Не понял вопроса...

я имел ввиду как найти айпи адреса для Пользовательского списка, но я уже наковырял, про ASN, выгрузил список адресов из ASN, так же нашёл доп адреса proton  и все адреса фейсбука. Ну иногда проблема с протоном появляется, там глубже если логиниться, то столкнешься тоже, скорее всего. Но я докопаюсь думаю до каждого айпишника. . Остальное работает хорошо :)

А, подскажи, как смотреть(чтобы закинуть это в Пользоват.список), куда сайт, который не загружается, пытается достучаться?

**Comment by 5k1n** [comment]
и еще вопросик, ruantiblock возможно подружить с adblock? как ?) (snapshot )

**Comment by gSpotx2f** [comment]
>твики из вики применял

Если вы про оптимизации блэклиста, то они работают только при использовании модуля-парсера на роутере (т.е. если роутер сам парсит реестр). В конфигурациях `ruantiblock-fqdn` и `ruantiblock-ip` скачиваются уже готовые файлы из [этого](https://github.com/gSpotx2f/ruantiblock_blacklist) репозитория, а оптимизации, фильтры и пр. не применяются (модуль-парсер, вообще, не задействован при обновлении списка).

>не нашёл, кстати, в чем разница принципиальная двух вариантов (fqdn / ip) , какой вариант лучше/быстрее ?

В общих словах, разница в том, что `fqdn` использует разрешение имён заблокированных сайтов во время запроса, поэтому ip адрес сайта всегда актуален, даже если сайт сменил ip. К тому же, в этой конфигурации обход блокировок более точный. В режиме `ip` просто добавляются все ip адреса из реестра, но на многих ip адресах висят сотни и тысячи сайтов (хостинги, CDN и пр.) и если заблокирован один сайт, то на все остальные сайты на этом ip, так же, трафик идёт через VPN.

>А, подскажи, как смотреть(чтобы закинуть это в Пользоват.список), куда сайт, который не загружается, пытается достучаться?

В браузере, в инструментах разработчика открыть консоль для отладки и смотреть соединения во вкладке "сеть". Например, так можно вычислить проблемные сторонние узлы с которых подгружается доп. контент (видео, изображения и пр.).

>и еще вопросик, ruantiblock возможно подружить с adblock? как ?) (snapshot )

Я никогда не пытался, ибо не пользуюсь блокировщиками рекламы на роутере. ИМХО, это не эффективно, блочить рекламу имеет смысл в браузере (там есть доступ к коду страницы, JS и т.п.). В общем, не разбирался в чём может быть несовместимость...

**Comment by 5k1n** [comment]
Спасибо, понял. а на снапшоте проверялась работспособность fdqn + httpsdnsproxy ? у меня такая конфа работает только с ip. через fdqn не загружает заблокированные и сайты из списка пользователя

**Comment by 5k1n** [comment]
> Настройте [перехват сторонних DNS-запросов](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D1%85%D0%B2%D0%B0%D1%82-%D1%81%D1%82%D0%BE%D1%80%D0%BE%D0%BD%D0%BD%D0%B5%D0%B3%D0%BE-DNS-%D1%82%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0)
Сделал, не помогло, всё равно fdqn не загружает сайты заблокированные и так же из списка пользователя. проверяю простым методом, помимо nnmclub rutracker, я так же добавил whoer.net для проверки айпи адреса. так вот на конфиге `ip `всё это работает(торренты открывает, whoer показывает ip vpn), а на `fdqn `заблокированные не грузит, а whoer показывает мой реальный ип.

Вот лог с fdqn, но он идентичен и на ip:

![Screenshot_7](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/104699534/2df807a4-f0c6-41df-a559-2d0d1af76f9c)

**Comment by 5k1n** [comment]
методом тестов понял, что у меня не работает dns https proxy, а ip конфиг работал, потому что brave бразуер сам сунул 1.1.1.1 в качестве днс.. хотя устанавливал всё по инструкции. и в luci статусы службы ОК

**Comment by 5k1n** [comment]
в общем переустановил dnsproxy, кажется всё заработало))

извини за раздувание проблемы)

спасибо большое!

**Comment by 5k1n** [comment]
![Screenshot_10](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/104699534/62f8e3a9-a314-4312-9472-3db4eee8058d)
какая то фигня в ДНС всё время добавляется. это норм?)

**Comment by gSpotx2f** [comment]
>какая то фигня в ДНС всё время добавляется. это норм?)

Наверное, добавляет какое-то приложение использующее DNS (https-dns-proxy, adblock и пр.). Ищите в настройках. Это уже не имеет отношения к данному проекту...
