### ISSUE TITLE
OpenWrt 23.05.0-rc1

### ISSUE THREAD

**Issue by samara1532** [gSpotx2f/ruantiblock_openwrt#32]
23.05.0-rc1  (AX6S)
нет в базе libubox20230523   (libubox-lua)

из-за чего естественно проблема с установкой вебприложения.
dnsmasq-full если поставить, то сразу ляжет dns
https-dns-proxy/dnscrypt если поставить то ляжет вообще вебморда  i.ibb.co/nsHhb1c/2.png

из мелочей, не поставилось автообновление блеклиста. добавлял ручками 
/etc/init.d/cron enable
echo "0 3 */3 * * /usr/bin/ruantiblock update" >> /etc/crontabs/root
/etc/init.d/cron restart

ну из нового, не нужно останавливать службу, что-бы получить доступ к расширенным настройкам (vpn/tor и т.п.)

**Comment by gSpotx2f** [comment]
[libubox20230523](https://downloads.openwrt.org/releases/23.05.0-rc1/packages/aarch64_cortex-a53/base/libubox20230523_2023-05-23-75a3b870-1_aarch64_cortex-a53.ipk) есть в репозитории для 23.05.
Зависимости поломаны у dnsmasq-full и libubox-lua (а может и где-то ещё). Нужно перед установкой dnsmasq-full поставить libubox20230523:

    opkg update
    opkg install libubox20230523

или скачайте пакет, там один файл libubox.so.20230523, положите его в папку `/lib` на роутере.

https-dns-proxy у меня работает без проблем в 23.05-rc1, может проблема в том же libubox...
Задание обновления в cron добавляет скрипт для автоинсталяции. При обычной установке пакетов вручную, задание нужно добавлять самостоятельно (в вики это прописано).

**Comment by samara1532** [comment]
ну можно сноску сделать в инструкции, что-бы пользователь проверил сначала что этот пакет установлен.

а то неопытный пользователь ставит
opkg --force-overwrite install dnsmasq-full

и потом баттхёрт , что следующие команды не проходят.  
не вчитываясь особо в ком. строке на ругатню по поводу libubox20230523
и запоздалое понимание что у тебя инет почему-то лёг.

по поводу скачать и положить, ну тут несколько моментов.
как не опытному пользователю, понять что нужно скачать, догадаться прописать на устройстве вручную днс для этого,
узнать где это скачать и под какую архитектуру, понять куда засунуть, иметь установленный sftp сервер.
мне проще сделать сброс и решить это простым путем)))


https-dns-proxy
ну я обновился сисапгрейдом и у меня этого пакета не оказалось.  и легла вебморда.
и я как истинный юзверь долбился в глаза и не сразу заметил на что ругатня.
