### ISSUE TITLE
Ruantiblock и mwan3

### ISSUE THREAD

**Issue by xplozyUA** [gSpotx2f/ruantiblock_openwrt#33]
Здравствуйте! Можно ли подружить эти 2 службы? После установки mwan3 даже без создания второго wan интерфейса перестает работать Ruantiblock (служба запущена без ошибок, в статистике правил iptables счетчик rc растет, но траффик идет через wan, а не wireguard)

**Comment by gSpotx2f** [comment]
mwan создаёт на роутере собственную сетевую конфигурацию (таблицу маршрутизации, правила iptables) для маршрутизации пакетов. Решения для обхода блокировок (как и блокировщики рекламы, vpn policy routing и другие подобные службы) очень серьёзно вмешиваются в основной функционал роутера, т.е. в управление пакетами, маршрутизацию и разрешение имён (DNS). Поэтому любые другие параллельные сервисы влияющие на сетевую конфигурацию, как правило, приводят к взаимным проблемам. Данный проект предполагает использование более или менее стандартной сетевой конфигурации роутера, либо самостоятельное допиливание под индивидуальную конфигурацию. Что касается конкретно mwan3, подозреваю что дело в метках пакетов в iptables (и ruantiblock, и mwan метят пакеты для отбора в правила маршрутизации).
Попробуйте заменить файл `/etc/ruantiblock/scripts/ipt_functions` на [этот](https://gist.github.com/gSpotx2f/272c6989b50e058fb268a0f87c74f9c8). Там я исправил команду добавления правила для ruantiblock, оно должно располагаться после правил mwan. Если не поможет, значит несовместимость глубже.

**Comment by xplozyUA** [comment]
Спасибо большое, на 22.03.5 все работает)

**Comment by gSpotx2f** [comment]
>на 22.03.5 все работает

Ок, добавил [коммит](https://github.com/gSpotx2f/ruantiblock_openwrt/commit/018009783191749391f44e53bf5ede17fe7f1088) с исправлениями.
