### ISSUE TITLE
Исключить из обхода

### ISSUE THREAD

**Issue by boozzze** [gSpotx2f/ruantiblock_openwrt#34]
Добрый день, подскажите, Как-то возможно исключить из обхода конкретный IP адрес? 
К моему ВПС в Нидерландах подключается через VPN

**Comment by gSpotx2f** [comment]
>К моему ВПС в Нидерландах подключается через VPN

Ваш VPS доступен напрямую, с отключенным ruantiblock?

>Как-то возможно исключить из обхода конкретный IP адрес?

В [обновлении](https://github.com/gSpotx2f/ruantiblock_openwrt/commit/ce79a1f469f0216060881f0f421d8190c7f6f8d8) v1.2 (для новой OpenWRT 23.05 или Snapshot) добавил возможность исключать IP адреса из обхода блокировок отдельным правилом nftables. В вебморде на вкладке "Настройки"->"Настройки блэклиста" или через UCI:

    uci set ruantiblock.config.bypass_ip_mode="1"
    uci add_list ruantiblock.config.bypass_ip_list="123.45.67.89"
    uci add_list ruantiblock.config.bypass_ip_list="123.45.67.90"
    uci commit

`123.45.67.89`, `123.45.67.90` и т.п. - пример IP для списка исключений.

**Comment by boozzze** [comment]
Спасибо большое! Да, впс доступен без впн!
Как обновить версию, чтобы не задеть текущие настройки?

**Comment by gSpotx2f** [comment]
Есть новые парметры в конфигурации, поэтому лучше [поставить заново](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-v1.1#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0). Перед этим удалите `/etc/ruantiblock/ruantiblock.conf`:

    rm /etc/ruantiblock/ruantiblock.conf

Если у вас свой список ("записи пользователя"), то он находится в файле `/etc/ruantiblock/user_entries`.

**Comment by boozzze** [comment]
То есть удаляю только 1 файл, и делаю бекап второго, далее иду по мануалу заново?

**Comment by boozzze** [comment]
понял! Спасибо! тестирую! чтобы вступало в силу - обновить блеклист жмем?

**Comment by boozzze** [comment]
после установки 1.2 https://prnt.sc/8y_qyb-IWDUm вот тут не было изменений. сделал через консоль.
появилась галочка и список со строчками. далее после обновления блеклиста через кнопку, тут опять стало пустою

**Comment by gSpotx2f** [comment]
После внесения адрсов в список bypass_ip, обновлять блэклист не нужно, правила добавляются в nftables после применения настроек. Если добавляете через консоль, то после необходимо перезапустить ruantiblock:

    ruantiblock restart

 чтобы новые правила заработали.
