### ISSUE TITLE
23.05.0-rc2

### ISSUE THREAD

**Issue by piroj0k** [gSpotx2f/ruantiblock_openwrt#36]
не могу установить ruantiblock-ошибка 404
`root@OpenWrt:~#` wget --no-check-certificate -O /tmp/ruantiblock_1.2-1_all.ipk https://raw.githubusercontent.com/gSpotx2f/packages-openwrt/master/23.05/ruantiblock_1.2-1_all.ipk`
Downloading 'https://raw.githubusercontent.com/gSpotx2f/packages-openwrt/master/23.05/ruantiblock_1.2-1_all.ipk'
Connecting to 185.199.109.133:443
HTTP error 404
root@OpenWrt:~#
других прошивок на мое устройство нет, помогите пожалуйста

**Comment by samara1532** [comment]
аналогично, не находит файлы по ссылке.

**Comment by gSpotx2f** [comment]
Исправил вики.
Кстати, по ссылкам совсем не трудно найти саму [папку](https://github.com/gSpotx2f/packages-openwrt/tree/master/23.05) с пакетами в репо.

**Comment by samara1532** [comment]
прости нас криворуких.

кстати на пакетах rc2  вылезла новая фича
опять этот https-dns-proxy  криво встает. (где еще вылезет хз)
хочет libnl-tiny2023-07-01 , а стоит libnl-tiny2023-04-02
и поставить новый не может, и вручную через менеджер "libnl-tiny уже и так стоит"

порешил его 
opkg --force-overwrite install libnl-tiny2023-07-01
