### ISSUE TITLE
Отсутствует резолв на клиентских устройствах Xiaomi Redmi Router AX6S

### ISSUE THREAD

**Issue by darkshines** [gSpotx2f/ruantiblock_openwrt#38]
Ставил модуль по статье Самостоятельная установка и настройка v1.1

FW: OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.093.57104-ce20b4a
Модуль DNS HTTPS Proxy  установлен

При включенном модуле не проходит резолв хостов, при этом на роутере все адреса резолвятся.

С клиентского устройства
nslookup habr.com
DNS request timed out.
    timeout was 2 seconds.
╤хЁтхЁ:  UnKnown
Address:  192.168.1.1

DNS request timed out.
    timeout was 2 seconds.
    
 с роутера
nslookup habr.com
Server:         8.8.8.8
Address:        8.8.8.8:53

Non-authoritative answer:

Non-authoritative answer:
Name:   habr.com
Address: 178.248.237.68

если выключить службу ruantiblock dns сразу начинает резолвится

рекомендации из статьи "Если после установки возникли проблемы..." применял, ничего не помогает

**Comment by darkshines** [comment]
Также заметил, что на роутере для интерфейса wg был прописан custom DNS

cat /etc/resolv.conf
# Interface wan
# Interface wgfin
nameserver 8.8.8.8
nameserver 8.8.4.4

после удаления записей, при включении службы antiblock резолв на роутере тоже перестает работать
 
# /usr/bin/ruantiblock update
 ruantiblock update...
 Received entries: CIDR: 650, IP: 5181, FQDN: 150995
 Blacklist updated
 Updating nft sets...
 Ok
udhcpc: started, v1.35.0
udhcpc: broadcasting discover
udhcpc: no lease, failing

# /usr/bin/ruantiblock status

 ruantiblock status: Enabled

  PROXY_MODE: 2
  PROXY_LOCAL_CLIENTS: 1
  BLLIST_PRESET: ruantiblock-fqdn
  BLLIST_MODULE: DownloadRuabBlacklist fqdn

  Last blacklist update:  19.08.2023-15:00 (CIDR: 650 | IP: 5181 | FQDN: 150995)

  Nftables rules:

   Match-set:  c
   Bytes:  0

   Match-set:  i
   Bytes:  0

   Match-set:  d
   Bytes:  0

# ping ya.ru
ping: bad address 'ya.ru'

**Comment by gSpotx2f** [comment]
>Ставил модуль по статье Самостоятельная установка и настройка v1.1

>FW: OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.093.57104-ce20b4a

В вики же русским по чёрному КРУПНО [написано](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-v1.1#ruantiblock-v11-%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B8%D0%BC-%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE-%D1%81-openwrt-2305-%D0%B8%D0%BB%D0%B8-%D0%BF%D1%80%D0%BE%D1%88%D0%B8%D0%B2%D0%BA%D0%B0%D0%BC%D0%B8-%D1%81%D0%BE%D0%B1%D1%80%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8-%D0%B8%D0%B7-snapshot-%D0%B2-%D1%81%D1%82%D0%B0%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8-openwrt-2203-dnsmasq-%D0%BD%D0%B5-%D0%B8%D0%BC%D0%B5%D0%B5%D1%82-%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B8-nftables): "Ruantiblock **_v1.1_** совместим только с OpenWrt **_23.05_** или прошивками собранными из snapshot. **_В стабильной версии OpenWrt 22.03 dnsmasq не имеет поддержки nftables!_**" А вы ставите ruantiblock 1.x на 22.03. Вангую, dnsmasq не может запуститься из-за конфига (потому что старая версия не поддерживает nftables), смотрите системный лог.
