### ISSUE TITLE
luci-app-ruantiblock не отображается в службах

### ISSUE THREAD

**Issue by Loncaster** [gSpotx2f/ruantiblock_openwrt#4]
После установки через автоскрипт данная служба не появилась в ui интерфейсе.
Версия: LuCI Master (git-21.280.14233-9b796b1)](https://github.com/openwrt/luci) / OpenWrt R21.11.11

**Comment by gSpotx2f** [comment]
Master - эксперементальная ветка для разработчиков, там бывают разные "сюрпризы". Я тестирую только стабильные релизы. Может проблема в кэше LuCI, попробуйте его очистить:

	rm /tmp/luci-indexcache* /tmp/luci-modulecache/*
	/etc/init.d/rpcd restart

Также очистите кэш браузера.

Сам ruantiblock работает, без веб-интерфейса?

	/usr/bin/ruantiblock status

**Comment by koroleves** [comment]
Спасибо! Вам огромное за комментарий! Пока не получается настроить, кажется WAN и TUN интерфейсы "конкурируют" друг с другом. Тунель пытался создать по этой инструкции. https://github.com/StreisandEffect/streisand/wiki/Setting-an-OpenWrt-Based-Router-as-OpenVPN-Client Она правильная?
