### ISSUE TITLE
raw.githubusercontent.com в блокировке

### ISSUE THREAD

**Issue by zalessky** [gSpotx2f/ruantiblock_openwrt#40]
raw.githubusercontent.com в блокировке. никак нельзя обновление блэклистов через тунель/проски принудительно? пользовательские листы не помогают, так как применяются **после** обновления блеклиста

<html>
<body>

11 | Fri Aug 25 10:33:14 2023 | notice | user | ruantiblock: update...
-- | -- | -- | -- | --
12 | Fri Aug 25 10:33:44 2023 | err | user | ruantiblock: Blacklist downloading failed! Connection error (https://raw.githubusercontent.com/gSpotx2f/ruantiblock_blacklist/master/blacklist/fqdn/ruantiblock.dnsmasq)
13 | Fri Aug 25 10:33:44 2023 | err | user | ruantiblock: Module run attempt 1: failed [DownloadRuabBlacklist fqdn]
14 | Fri Aug 25 10:35:16 2023 | err | user | ruantiblock: Blacklist downloading failed! Connection error (https://raw.githubusercontent.com/gSpotx2f/ruantiblock_blacklist/master/blacklist/fqdn/ruantiblock.dnsmasq)
15 | Fri Aug 25 10:35:16 2023 | err | user | ruantiblock: Module run attempt 2: failed [DownloadRuabBlacklist fqdn]
16 | Fri Aug 25 10:36:46 2023 | err | user | ruantiblock: Blacklist downloading failed! Connection error (https://raw.githubusercontent.com/gSpotx2f/ruantiblock_blacklist/master/blacklist/fqdn/ruantiblock.dnsmasq)
17 | Fri Aug 25 10:36:46 2023 | err | user | ruantiblock: Module run attempt 3: failed [DownloadRuabBlacklist fqdn]
18 | Fri Aug 25 10:36:46 2023 | err | user | ruantiblock: Module error! [DownloadRuabBlacklist fqdn]

</body>
</html>

**Comment by gSpotx2f** [comment]
`raw.githubusercontent.com` доступен, с чего вы взяли, что он заблокирован?

Включите режим обновления блэклиста "Только записи пользователя", добавьте `raw.githubusercontent.com` в записи пользователя, обновите блэклист. Проверьте доступен ли `raw.githubusercontent.com`. Затем режим обновления блэклиста переключите в `ruantiblock-fqdn` и обновите блэклист.

**Comment by zalessky** [comment]
Сейчас доступен. Но его регулярно блочат. 
Включал. доступ к raw.githubusercontent.com появлялся через обходчик. 
Но если обратно переключить на ruantiblock-fqdn и обновить блеклист, то списки начинают качаться опять напрямую и скачаться не могут, пока не закончится блокировка. Замкнутый круг

**Comment by zalessky** [comment]
у меня снова не ходит на raw.githubusercontent.com
Как воспользоваться новой опцией?

**Comment by gSpotx2f** [comment]
>Как воспользоваться новой опцией?

[Установить последнюю версию ruantiblock](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-v1.1) для OpenWrt 23.05. На странице _Ruantiblock->Настройки->Настройки блэклиста_ включить чекбокс `Скачивать блэклист через прокси` и применить настройки...

**Comment by zalessky** [comment]
Ну так хост https://raw.githubusercontent.com/gSpotx2f/packages-openwrt/master/23.05/ruantiblock_1.3-0_all.ipk тоже в блоке

**Comment by zalessky** [comment]
Скачал руками. обновил. нет там такой опции

**Comment by samara1532** [comment]
дабы не плодить темы спрошу тут.
как при прозрачном прокси отключить спам сообщений в системном журнале
 daemon.info /usr/bin/ss-redir[20297]: redir to ххххххххххх:443, len=140, recv=140

**Comment by zalessky** [comment]
@gSpotx2f ну когда же будет доступна новая версия 0.9.**8** с опцией опцию для обновления блэклиста через прокси или VPN?

**Comment by gSpotx2f** [comment]
Ветка 0.9 больше не развивается, там обновлений не будет (только исправления существенных багофиксов, если появятся. И то не факт...)

**Comment by zalessky** [comment]
А как быть, если Nft set wasn't updated? на последней версии? Работает лишь 0.9 :(
```
# opkg list ruantiblock
ruantiblock - 0.9.7-1
```

**Comment by zalessky** [comment]
[openwrt-22.03 branch (git-23.039.29681-007c243)](https://github.com/openwrt/luci) / OpenWrt 22.03.2 r19803-9a599fee93
[отсюда](https://4pda.to/forum/index.php?showtopic=837667&st=28920#entry119380353)
