### ISSUE TITLE
yt3.ggpht.com

### ISSUE THREAD

**Issue by anomalyQC** [gSpotx2f/ruantiblock_openwrt#42]
Проблема в долгом запуске ролика на ПК, при открытии DevTools видно, что идет запрос https://rr1---sn-xguxaxjvh-3w5e.googlevideo.com/..../ip=адрес впн. Иногда работает нормально, все грузится быстро (при этом в запросе стоит провайдерский айпи), аватарки также на месте. Можно ли это как-то поправить? Например, при использовании антизапрета, проксируются только аватарки, проблем с долгой загрузкой видео нет.

**Comment by gSpotx2f** [comment]
Проблемы с youtube возникают из-за DNS: гугловский домен `yt3.ggpht.com` (заблокирован и находится в реестре, там лежат аватарки) иногда резолвится в тот же IP-адрес что и домен youtube.com. Поэтому сайт youtube.com открывается через VPN (это видно по коду страны на странице), что приводит ко всяким странностям (появляется иностранная реклама и т.п.). Видеоконтент идёт напрямую с домена `googlevideo.com`, а поскольку ссылки для запросов API формирует JS в браузере, то он подставляет тот IP с которого загрузилась страница. Во всяком случае, я это так вижу. У меня тоже пару месяцев назад, часто по вечерам, видео стартовало с задержкой и youtube отображал страну VPN, по вышеописанной причине, но сейчас этой проблемы нет. Если у вас OpenWrt 23.05 и последняя версия ruantiblock, то в принципе, можно добавить `yt3.ggpht.com` в список исключений блэклиста, тогда не будет аватарок на youtube, но и проблема с воспроизведением должна решиться. Ещё можно попробовать сменить DNS-сервер в https-dns-proxy (с google на cloudflare, например).

**Comment by anomalyQC** [comment]
Спасибо за ответ! А почему при использовании антизапрета такой проблемы нету, не знаете случайно? Так же, если смотреть с телефона, то всё окей. Использую dnscrypt, там настроены сервера quad9, может стоит сменить сервера на самой VPS?

**Comment by gSpotx2f** [comment]
Чисто предположения... На смартфоне, наверняка, смотрите через приложение, а приложение работает по другому (использует API и не загружает сайт youtube.com как браузер). Про анитизапрет я не в курсе, никогда им не пользовался, но у них вроде свой DNS-резолвер, на который отправляются все ваши запросы, соответственно там `youtube.com` и `yt3.ggpht.com` резолвятся по другому. Вот у меня сейчас тоже всё нормально работает, а в середине лета были проблемы. Вообще, я подозреваю, что задержка запуска видео связана с показом рекламного ролика перед видео. В URL запроса видео с домена `googlevideo.com` добавляется IP-адрес (для геолокации рекламы?), с которого открыта страница youtube.com. А так как googlevideo.com доступен напрямую, получается, что рекламное видео предназначенное для региона IP-адреса из URL (VPN) не доступно из РФ (где сейчас отключена вся реклама и монетизация). Поэтому возникает задержка при попытке показать недоступный рекламный ролик перед открытием видео на сайте youtube.com. Это моё ИМХО...

>может стоит сменить сервера на самой VPS?

DNS-серверы надо менять там, где у вас резолвятся адреса для вашей домашней сети. Если dnscrypt на роутере работает напрямую, то в нём. Если dnscrypt на VPS, то там.
