### ISSUE TITLE
Замена ipset на nftset

### ISSUE THREAD

**Issue by nologin789** [gSpotx2f/ruantiblock_openwrt#43]
В последних версиях OpenWRT из пакета dnsmasq убрана поддержка ipset, оставлена только nftset. По этой причине после включения ruantiblock, dnsmasq падает с ошибкой:
 dnsmasq[1]: recompile with HAVE_IPSET defined to enable ipset directives

**Comment by samara1532** [comment]
ну так и ставь  на последнюю версию OpenWRT, последнюю версию  руантиблок 1.3
