### ISSUE TITLE
несовместимая архитектура

### ISSUE THREAD

**Issue by zalessky** [gSpotx2f/ruantiblock_openwrt#44]
Обновил роутер. Настраиваю... 
[Askey RT4230W (Askey RAC2V1K)](https://4pda.to/forum/index.php?showtopic=1036016&st=20)
CPU1: Qualcomm IPQ8065 (1.7 GHz, 2 cores)

Модель	Askey RT4230W REV6
Архитектура	ARMv7 Processor rev 0 (v7l)
Целевая платформа	ipq806x/generic
Версия прошивки	OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.119.80898-65ef406
Версия ядра	5.10.176

Не устанавливается пакет luci-i18n-ruantiblock-ru_1.3-0_all.ipk

```
root@OpenWrt:~$ opkg install ./luci-i18n-ruantiblock-ru_1.3-0_all.ipk
Unknown package 'luci-i18n-ruantiblock-ru'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-i18n-ruantiblock-ru
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-i18n-ruantiblock-ru found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-i18n-ruantiblock-ru.

```

**Comment by gSpotx2f** [comment]
>Версия прошивки OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.119.80898-65ef406

>Не устанавливается пакет luci-i18n-ruantiblock-ru_1.3-0_all.ipk

Во-первых, вы опять наступаете на те же грабли. Мы уже обсудили ранее, что ветка ruantiblock v1.x для OpenWrt 23.05, а вы пытаетесь установить его на 22.03! Когда вы его установите, оно работать не будет. Смотрите [23.05 для вашего девайса](https://firmware-selector.openwrt.org/?version=23.05.0-rc4&target=ipq806x%2Fgeneric&id=askey_rt4230w-rev6)

Во-вторых, архитектура не может быть несовместимой, ибо все пакеты ruantiblock собраны для архитектуры `all`, т.е. не зависят от платформы (там нет бинарных файлов, только скрипты). Кстати, у меня роутер с такой же архитектурой IPQ8065 (Zyxel Armor Z2). Проблема в неразрешённой зависимости - не установлен пакет `luci-lua-runtime`. `opkg update` делали перед установкой пакета?

**Comment by zalessky** [comment]
Блин. Действительно... Пардон... 
Не собирается прошивка ни из релизкандидатов, ни из снапшота. Версии ядра не соответствуют у половины пакетов. Придется дальше страдать. Скоро зарелизится - вот тогда и развернемся

**Comment by zalessky** [comment]
Дождался релиза 23.05.0. Собрал прошивку для своего RT4230W
К ruantiblock претензий никаких: вижу по трассировке, что после включения пакеты начинают ходить через нужный интерфейс. Т.е. маршрутизация работает. Пинги (ping -I wg0 ya.ru) через VPN тоже ходят бодро. НО... wget до хоста из списка блеклиста говорит Failed to send request: Operation not permitted, а в браузере ERR_TIMED_OUT
раз 10 пересобирал все заново. куда копать, ума не приложу. :(

**Comment by gSpotx2f** [comment]
Какой режим обновления блэклиста? Шифрование DNS настроено? Трассировку, ping и wget вы делаете с роутера или с ПК? Ещё, в браузере (и в мобильных устройствах) нужно отключить "Безопасный DNS", чтобы он использовал системный DNS-сервер.

**Comment by zalessky** [comment]
для тестов блеклист только пользовательский. в блеклисте несколько доменов. В т.ч. 2ip.ru - так проще в браузере проверять работу. Обновляю вручную. Шифрование настраивал - не в нем дело. Сейчас использую собственный DNS Pi-hole, поднятый в облаке. Безопасный DNS отключен. Домены из блеклиста резолвятся правильно.
Трассировку делаю на роутере, на сервере VPN и на компе. 
когда поднят интерфейс VPN и включен руантиблок, для доменов в блеклисте трассировка на роутере и на сервере идентична (за исключением первого хопа для роутера). И пинги через интерфейс VPN ходят. Но больше ничего.

**Comment by zalessky** [comment]
Поднял sing-box по [этому мануалу](https://habr.com/ru/articles/767458/) 
Удивительно, но все наконец-то заработало. За одним исключением: после ребута роутера, ruanriblock вываливает ошибку "Ошибка маршрутизации VPN! Необходим перезапуск"
После рестарта работает стабильно. Предположу, что не успевает интерфейс подняться. Нет ли  скрипте возможности установить паузу перед запуском?

**Comment by gSpotx2f** [comment]
Ошибка маршрутизации - сообщение о том, что в данный момент нет маршрута на VPN-интерфейс (он отсутствует, т.е. ещё не поднялся). Когда VPN-интерфейс поднимается срабатывает скрипт `/etc/hotplug.d/iface/40-ruantiblock`, который добавляет маршрут. Поэтому, если ruantiblock запускается раньше чем поднимается VPN-интерфейс - это не проблема.

Ещё, я не пойму, вы писали выше, что у вас VPN (OpenVPN, Wireguard, PPtP и пр.), а теперь sing-box? Какая у вас кофигурация вообще?

**Comment by zalessky** [comment]
Ну да, я заметил, что хоть в веб-морду ругается, но работает. 

У меня со старых времен бесплатный виртуальный сервер у Oracle крутится. Хостер регулярно грозится прибить его из-за низкой загрузки :) Есть простор, где разгуляться. 

Новый роутер покупал специально для того, чтобы весь зоопарк поместился. Xray на x3g не влез. Интернет у меня в частном доме мобильный (модем Fibicom 860 до 300мб/с прокачивает). Поэтому последние месяцы попадаю под регулярные ковровые блокировки по протоколам. WG хорошо и быстро, поднимается левой ногой, но и блочится запросто. Даже Outline блочат, демоны. Вот и пробую разные новые протоколы в надежде, что их не забанят в обозримом будущем. Однако, вчера вечером IP моего сервера под блокировки попал. Чую, нужно запасной аэродром готовить :)

**Comment by gSpotx2f** [comment]
Всё-таки [добавил](https://github.com/gSpotx2f/ruantiblock_openwrt/blob/73b48cf71ef4f332ee219aeb890c5006053fe31b/ruantiblock/files/etc/hotplug.d/iface/40-ruantiblock#L8) задержку перед созданием маршрута после поднятия интерфейса в `/etc/hotplug.d/iface/40-ruantiblock`.

Чтобы не переустанавливать пакет, можете просто скачать этот файл на роутере:

    wget --no-check-certificate -O /etc/hotplug.d/iface/40-ruantiblock https://raw.githubusercontent.com/gSpotx2f/ruantiblock_openwrt/master/ruantiblock/files/etc/hotplug.d/iface/40-ruantiblock
