### ISSUE TITLE
просто к сведению

### ISSUE THREAD

**Issue by zalessky** [gSpotx2f/ruantiblock_openwrt#46]
пакеты luci-app-xray и luci-app-xray-shared конфликтуют с работой скрипта. если нужны новые неблокируемые VPN, можно пользоваться sing-box. luci интерфейса нет, зато работает стабильно и настройка несложная. инструкция по установке и настройке [тут](https://habr.com/ru/articles/767458/)  
инструкция как QR код переводить в готовый конфиг outbounds для sing-box [тут](https://4pda.to/forum/index.php?showtopic=1074012&view=findpost&p=124347656) 
Таким же макаром можно и SS Outline конфиг выдрать

**Comment by gSpotx2f** [comment]
Добавил [инфу по sing-box](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-ruantiblock-%D0%B4%D0%BB%D1%8F-%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%BD%D0%BE%D0%B9-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D0%BF%D1%80%D0%BE%D0%BA%D1%81%D0%B8-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%BE%D0%BC-sing%E2%80%91box) в вики.
