### ISSUE TITLE
Здравствуйте. В логах новый прикол.

### ISSUE THREAD

**Issue by Chuguevskiy** [gSpotx2f/ruantiblock_openwrt#48]
Здравствуйте. Спустя год пользования этим решением решил обновить openwrt на актульную релизную версию 23.05.0. Пришлось заново  все настраивать по инструкции(WireGuard-CloudFlare+ruantiblock). Столкнулся с бедой в логах:
![log](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/400950/d1c72c19-b7d4-42c0-ae86-6652ece98646)

NetworkError
HTTP error 404 while loading class file "/luci-static/resources/view/log/log-base.js?v=git-23.306.39416-c86c256"
  at compileClass (http://192.168.1.1/luci-static/resources/luci.js?v=git-23.306.39416-c86c256:168:16)

Plz help me!
Add:
Ура! Лог поправлен. Скачал фикс - фикс, почистил кеш и все взлетело. Спасибо gSpotx2f  !!!
![Log поправлен ;)](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/400950/1288fb9c-52b7-4463-aed6-165df4ae5717)

**Comment by Spp595** [comment]
Подтверждаю, то же самое
openwrt 23.05.0
runantiblock установлен 3 дня назад

**Comment by gSpotx2f** [comment]
Был баг с логом. Уже исправил. На роутере скачайте файл, чтобы не переустанавливать пакет luci-app-ruantiblock:

    wget --no-check-certificate -O /www/luci-static/resources/view/ruantiblock/log-widget.js https://raw.githubusercontent.com/gSpotx2f/ruantiblock_openwrt/master/luci-app-ruantiblock/htdocs/luci-static/resources/view/ruantiblock/log-widget.js

Потом очистите кэш браузера обязательно.
