### ISSUE TITLE
Доступ к локальной сети vpn

### ISSUE THREAD

**Issue by Spp595** [gSpotx2f/ruantiblock_openwrt#49]
Я хотел бы получать доступ к сети впн 10.66.66.0
Добавлял в файл blacklist 10.66.66.0/24, но это не работает. У меня сработало только добавление конкретного устройства 10.66.66.10
Как это правильно сделать?

**Comment by gSpotx2f** [comment]
Не понял вопроса, объясните развёрнуто, что вы хотите сделать.
10.66.66.0 - это локальный адрес, нет никакого смысла добавлять его в блэклист для обхода блокировок.
Если у вас две VPN сети и пр., то нужно смотреть в сторону pbr (Policy-Based Routing).

**Comment by Spp595** [comment]
Для обхода блокировок я использую vpn wireguard с ip сети 10.66.66.0, к этой сети также покдлючего устройство 10.66.66.10 и мне нужно получить к нему доступ и желательно получить доступ ко всем устройствам это сети т.е 10.66.66.5 10.66.66.7 и т.п без ввода каждого в список перенаправления

**Comment by Spp595** [comment]
И ещё кстати, сейчас пытался настроить Перехват стороннего DNS трафика по инструкции из Вики и после введения комманд и перезапуска роутера не работает днс(((( уже удалил из конфига файвола добавленные строки и все равно не работает

**Comment by gSpotx2f** [comment]
>к этой сети также покдлючего устройство 10.66.66.10 и мне нужно получить к нему доступ и желательно получить доступ ко всем устройствам это сети т.е 10.66.66.5 10.66.66.7 и т.п без ввода каждого в список перенаправления

Это не имеет отношения к **обходу блокировок** и данному проекту. Нельзя добавлять в блэклист локальные адреса, вы пытетесь использовать ruantiblock не по назначению! Вам нужны правила маршрутизации из локальной сети в сеть 10.66.66.0 (Policy-Based Routing).

>И ещё кстати, сейчас пытался настроить Перехват стороннего DNS трафика по инструкции из Вики и после введения комманд и перезапуска роутера не работает днс(((( уже удалил из конфига файвола добавленные строки и все равно не работает

Сейчас это уже не актуально, luci-app-https-dns-proxy сам умеет добавлять такие правила, если включено в настройках.
