### ISSUE TITLE
Logs error in LuCI?

### ISSUE THREAD

**Issue by flurmind** [gSpotx2f/ruantiblock_openwrt#5]
Спасибо за приложение, все работает, но при попытке зайти в лог в LuCI выдает ошибку, что это может быть (установлена RAM-конфигурация на Redmi AC2100)?
`NetworkError
HTTP error 404 while loading class file "/luci-static/resources/view/log/abstract-log.js?v=git-22.119.37126-a993714"
  at compileClass (http://192.168.0.10/luci-static/resources/luci.js?v=git-22.119.37126-a993714:168:16)
  at async Promise.all (index 2)`

**Comment by gSpotx2f** [comment]
Там был баг с импортом модуля. Уже исправил. Вообще, лучше переустановить приложение заново.
