### ISSUE TITLE
не работает после установки iptables-legacy 

### ISSUE THREAD

**Issue by Spp595** [gSpotx2f/ruantiblock_openwrt#50]
После установки пакетов iptables-legacy в openwrt 22.03.03 пропадает сеть и работает только на самом роутере

**Comment by Spp595** [comment]
Отвал сети происходит после конфигурации kmod-nf-ipt

**Comment by gSpotx2f** [comment]
>После установки пакетов iptables-legacy в openwrt 22.03.03 пропадает сеть и работает только на самом роутере

Здесь раздел для багов проекта **ruantiblock**. Проблемы с установкой iptables не имеют никакого отношения к этому проекту.

**Comment by Spp595** [comment]
Проблема в самом роутере из за snapshot репо
