### ISSUE TITLE
ruantiblock не работет из беспроводной сети.

### ISSUE THREAD

**Issue by Bazo0Z0o** [gSpotx2f/ruantiblock_openwrt#51]
Добрый день. Правила ruantiblock не применяются к трафику из беспроводной сети до тех пор, пока хотя бы один запрос к любому из хостов из блэк листа не будет произведен из проводно сети

**Comment by Bazo0Z0o** [comment]
Проблема в опции "Использовать безопасный DNS-сервер" в настройках приватности браузера, которая по умолчанию включена.
[Вот видео как её отключить](https://youtube.com/shorts/7xSmbKPlBxE?si=Pp8DUmf7aLIYibbB)

**Comment by gSpotx2f** [comment]
>Проблема в опции "Использовать безопасный DNS-сервер" 

В wiki об этом давно написано
