### ISSUE TITLE
Связь

### ISSUE THREAD

**Issue by MisharUser** [gSpotx2f/ruantiblock_openwrt#52]
Здравствуйте, хотел бы с вами связаться
Если это возможно напишите пожалуйста мне в Телеграм https://t.me/GenSShine2Im

**Comment by gSpotx2f** [comment]
Здравствуйте. Я не занимаюсь персональной техподдержкой или консультациями. Если нашли баг в этом проекте, можете создать тикет с описанием проблемы.
