### ISSUE TITLE
Не запускается ruantiblock после перезагрузки роутера

### ISSUE THREAD

**Issue by nitro3188** [gSpotx2f/ruantiblock_openwrt#56]
Добрый день. Использую Tor конфигурацию, всё делал по инструкции ([https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/Самостоятельная-установка-и-настройка]), работает, однако после перезагрузки лог выглядит так:
12 | Sun Mar 3 10:34:06 2024 | notice | user | ruantiblock: Received entries: CIDR: 616, IP: 5353, FQDN: 180705
13 | Sun Mar 3 10:34:06 2024 | notice | daemon | procd: /etc/rc.d/S99ruantiblock: Blacklist updated
14 | Sun Mar 3 10:34:06 2024 | notice | user | ruantiblock: Blacklist updated
15 | Sun Mar 3 10:34:06 2024 | notice | daemon | procd: /etc/rc.d/S99ruantiblock: Updating nft sets...
16 | Sun Mar 3 10:34:06 2024 | notice | daemon | procd: /etc/rc.d/S99ruantiblock: Ok
17 | Sun Mar 3 10:34:06 2024 | notice | daemon | procd: /etc/rc.d/S99ruantiblock: udhcpc: started, v1.36.1
18 | Sun Mar 3 10:34:06 2024 | notice | daemon | procd: /etc/rc.d/S99ruantiblock: udhcpc: broadcasting discover
19 | Sun Mar 3 10:34:09 2024 | notice | daemon | procd: /etc/rc.d/S99ruantiblock: udhcpc: no lease, failing

так должно быть?

**Comment by gSpotx2f** [comment]
Что конкретно вас смущает в логе? ruantiblock запустился, успешно скачал блэклист, сеты nftables обновились... В чём проблема?

**Comment by nitro3188** [comment]
спасибо за ответ! "no lease, failing" - вот это смутило.

**Comment by gSpotx2f** [comment]
>"no lease, failing" - вот это смутило.

Это не ruantiblock, а dhcp-клиент пишет в консоль. После обновления блэклиста ruantiblock перезапускает dnsmasq, а он за собой тянет перезапуск dhcp.
