### ISSUE TITLE
RuAntiBlock + AdGuard Home possible?

### ISSUE THREAD

**Issue by KotaruProject** [gSpotx2f/ruantiblock_openwrt#60]
Доброго времени суток. Скажите, возможно ли как то связать OWRT + RuAntiblock (Sing-box в качестве обхода блокировки) и сервер AdGuard Home (локальный). Возможно ли это все объединить, чтобы работал обход и была блокировка рекламы или же нет? 

Характиристики:
Роутер с OWRT 23.05.3
Пакеты RuAntiBlock + Sing-box
Локальный сервер на котором стоит AdGuard Home.

**Comment by gSpotx2f** [comment]
Про блокировщики рекламы на роутере не в курсе, никогда не пользовался. AdGuard Home - это, как я понимаю, сторонний DNS-сервер, который заменяет собой стандартный DNS-сервер OpenWrt (dnsmasq). Dnsmasq является одной из главных частей системы обхода блокировок. Следовательно, подружить AdGuard и ruantiblock не получится.

**Comment by KotaruProject** [comment]
> Про блокировщики рекламы на роутере не в курсе, никогда не пользовался. AdGuard Home - это, как я понимаю, сторонний DNS-сервер, который заменяет собой стандартный DNS-сервер OpenWrt (dnsmasq). Dnsmasq является одной из главных частей системы обхода блокировок. Следовательно, подружить AdGuard и ruantiblock не получится.

Поковырялся в настройках и в принципе выяснил, что подружить можно, если выбрать не fqdn, а ip.
Во втором случае обход работает даже с AdGuard Home. Благодарю за ответ. Вопрос решен!

**Comment by serega404** [comment]
По идее можно если сделать Клиент->dnsmasq->Adguard->google/cloudflare
