### ISSUE TITLE
после установки на 23.05.х ломает ddns

### ISSUE THREAD

**Issue by blahdy** [gSpotx2f/ruantiblock_openwrt#62]
после долгого использования на ветке 21 обновился и словил отвал ddns после установки ruantiblock. в логах дднс пишет 
204702 ERROR : uclient-fetch Error: '4'
 204702       : Failed to send request: Operation not permitted
анинсталл не помогает, только сброс роутера.

п.с.
на ветке 24.х то же самое
Антиблок работает сам нормально

**Comment by blahdy** [comment]
После небольшого копания - становится недоступен v6 адрес afraid.org именно для роутера, с устройств пингуется нормально

**Comment by gSpotx2f** [comment]
Про ddns, вообще, не в курсе. ruantiblock использует dns для обхода блокировок, поэтому возможно несовместимость.

>И это сохраняется после удаления руантиблока

afraid.org нет в списке блокировок. После полного отключения ruantblock (а тем более после удаления) он никак не влияет на работу роутера (удаляются все правила и маршруты которые он создаёт).

**Comment by Wiedzmin89** [comment]
Вроде бы получилось победить проблему, поставив следующие настройки в DDNS -> Advanced settings:

![image](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/61706855/5bfc699a-ca28-44c9-912b-ef81d8f48d23)

**Comment by Wiedzmin89** [comment]
Вроде бы удалось решить эту проблему, слежующими параметрами в настройках ddns:

![image](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/61706855/2de59e71-4857-46fd-afe7-4d7045e0b4aa)

**Comment by blahdy** [comment]
> Вроде бы удалось решить эту проблему, слежующими параметрами в настройках ddns:
> 
> ![image](https://private-user-images.githubusercontent.com/61706855/329745806-2de59e71-4857-46fd-afe7-4d7045e0b4aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTI3NzUsIm5iZiI6MTcxNTQxMjQ3NSwicGF0aCI6Ii82MTcwNjg1NS8zMjk3NDU4MDYtMmRlNTllNzEtNDg1Ny00NmZkLWFmZTctNGQ3MDQ1ZTBiNGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA3Mjc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YmNkYzAwZDE0ZTljNmUwM2EyN2ZkMDczYmI4NjEyZjlmM2E5ZDdhNGVkNmU5OTI0ZTE3NWNkYzQ4N2IxMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P48gPl3Jp17M61-yP1Hb5ZqMRBF69Qdhk5eLE1iY7SQ)

Force ip version или сервером днс?

если второе, то, думается, дело в ипв6 адресе afraid
Я решил проблему переходом на dynv6, но это не решение

**Comment by Wiedzmin89** [comment]
> > Вроде бы удалось решить эту проблему, слежующими параметрами в настройках ddns:
> > ![image](https://private-user-images.githubusercontent.com/61706855/329745806-2de59e71-4857-46fd-afe7-4d7045e0b4aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTI3NzUsIm5iZiI6MTcxNTQxMjQ3NSwicGF0aCI6Ii82MTcwNjg1NS8zMjk3NDU4MDYtMmRlNTllNzEtNDg1Ny00NmZkLWFmZTctNGQ3MDQ1ZTBiNGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA3Mjc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YmNkYzAwZDE0ZTljNmUwM2EyN2ZkMDczYmI4NjEyZjlmM2E5ZDdhNGVkNmU5OTI0ZTE3NWNkYzQ4N2IxMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P48gPl3Jp17M61-yP1Hb5ZqMRBF69Qdhk5eLE1iY7SQ)
> 
> Force ip version или сервером днс?

И то и другое
