### ISSUE TITLE
Не работает только список пользователя

### ISSUE THREAD

**Issue by RombI4123** [gSpotx2f/ruantiblock_openwrt#63]
На версии 1.4.3 вставлял в пользовательский список ип с antifilter.download. В версии 1.5 такой метод не работает

**Comment by gSpotx2f** [comment]
>На версии 1.4.3 вставлял в пользовательский список ип с antifilter.download. В версии 1.5 такой метод не работает

Что именно не работает? Какой конкретно файл с antifilter.download? В чём смысл этого тикета, если вы не даёте никакой информации о проблеме?

У записей пользователя есть определённый формат, который [описан в вики](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D0%B8-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F-%D0%B2-%D0%B1%D0%BB%D1%8D%D0%BA%D0%BB%D0%B8%D1%81%D1%82%D0%B5) и в вебморде. Записи пользователя не предназначены для больших списков! Если нужен полный обход по реестру, то необходимо либо использовать стандартную конфигурацию (с выгрузкой готовых блэклистов), либо [доустановить модуль-парсер](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/Lua%E2%80%91%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C) для собственной конфигурации. Кстати, antifilter.download поддерживается парсером как источник блэклиста (список [allyouneed.lst](https://antifilter.download/list/allyouneed.lst)).

**Comment by Shkarlatov** [comment]
Использую версию `luci-app-ruantiblock_1.5-1_all`, столкнулся с такой же проблемой:
Использую режим VPN + только записи пользователя  -  не проксирует. 

Пример моих записей:
```
intel.com
www.intel.com
2ip.ru
```
ark.intel.com = запрёщен доступ с РФ IP
2ip.ru = показывает мой реальный ip 

Так же заметил что в логе пишет на рестарт сервиса пишет  `ruantiblock: User entries (local): CIDR: 0, IP: 0, FQDN: 0`
![image](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/1247023/7160ff97-8453-4cb7-bb90-42f29a2869d5)
![image](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/1247023/7b77d70d-258a-4cb9-829a-dae4d1cd84d6)

**Comment by RombI4123** [comment]
allyouneed.lst. Просто копировал список и вставлял /etc/ruantiblock/user_entries. Раньше работало сейчас не хочет

**Comment by gSpotx2f** [comment]
>Раньше работало сейчас не хочет.

Ещё раз: опишите как именно не работает. Какие-то сообщения об ошибках при обновлении, какие конкретно симптомы? Сейчас проверил у себя, добавил содержимое файла [allyouneed.lst](https://antifilter.download/list/allyouneed.lst) в `user_entries` и обновил блэклист - всё нормально работает, файл совместим с форматом `user_entries`.

**Comment by RombI4123** [comment]
![image](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/39383152/62a1fe37-cfec-400a-af5e-d25f4218600c)
как я понял блеклист обновляется, но как то до конца процесс не доходит

**Comment by RombI4123** [comment]
Sun May 26 16:26:23 2024 user.notice ruantiblock: update...
Sun May 26 16:26:24 2024 user.notice ruantiblock: Blacklist updated
Sun May 26 16:26:24 2024 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: started, version 2.90 cachesize 1000
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: DNS service limited to local subnets
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack no-ipset nftset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: UBus support enabled: connected to system bus
Sun May 26 16:26:28 2024 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.1.100 -- 192.168.1.249, lease time 12h
Sun May 26 16:26:28 2024 daemon.info dnsmasq-dhcp[1]: IPv6 router advertisement enabled
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for test
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for local
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for lan
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: reading /tmp/resolv.conf.d/resolv.conf.auto
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using nameserver 1.1.1.1#53
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using nameserver 1.0.0.1#53
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using nameserver 1.1.1.1#53
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using nameserver 8.8.8.8#53
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using nameserver 77.88.8.8#53
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for test
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for local
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: using only locally-known addresses for lan
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: read /etc/hosts - 12 names
Sun May 26 16:26:28 2024 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 2 names
Sun May 26 16:26:28 2024 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses

**Comment by gSpotx2f** [comment]
Покажите вывод команды `nft list set ip r c` после обновления блэклиста (со списком из allyouneed.lst в user_entries).

**Comment by RombI4123** [comment]
![image](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/39383152/d958395e-8297-438f-88b0-c28d28502641)

**Comment by gSpotx2f** [comment]
Записи из user_entries не добавляются в сет nftables, но по логам всё нормально, ошибок нет. Вы же из под Windows работаете? Как добавляете содержимое [allyouneed.lst](https://antifilter.download/list/allyouneed.lst) на роутер? Есть подозрение на символ окончания строки. В Windows `\r\n`, а в Linux `\n`. Встроенный парсер ruantiblock, который разбирает содержимое user_entries, игнорирует строки не соответствующие шаблону ip-адреса или домена. Получается, что для парсера записи выглядят так:

    1.179.201.0/24\r
    2.2.2.0/24\r
    2.16.16.0/24\r
    2.16.27.0/24\r
    и т.д.

вместо

    1.179.201.0/24
    2.2.2.0/24
    2.16.16.0/24
    2.16.27.0/24
    и т.д.

Кстати, в последних версиях ruantiblock добавлена опция позволяющая подключать удалённый файл user_entries по URL. Т.е. можно https://antifilter.download/list/allyouneed.lst добавить как удалённый файл и обновлять по расписанию.
![](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/25307679/6d7d7f61-a026-4066-ae05-1169d54f7e5e)

**Comment by RombI4123** [comment]
Я просто открывал через винсцп и вставлял. Поменялось только версия руантиблока(с 1.4.3 на 1.5) и опенврт (с 23.05.0 на 05.3). Сейчас по новому попробовал. Вроде все работает. Спасибо
![image](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/39383152/c92c590e-e2da-40ed-837d-137d4cf0a85f)
![image](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/39383152/ed06e9d1-6f99-46e8-ac09-3c8128b99743)
![image](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/39383152/08f3f9fe-21ff-47df-b71f-d9875ae337c2)
