### ISSUE TITLE
Ruantiblock + tailscale

### ISSUE THREAD

**Issue by Alexey71** [gSpotx2f/ruantiblock_openwrt#64]
Здравсвуйте. Настроен `Ruantiblock` в режиме VPN (Wireguard). Все хорошо работает. Но вот еще установлен `Tailscale`, чтобы я с внешки мог в роутер заходить. В `Tailscale` есть режим `exit node`, это телефон использует роутер для доступа к интернету, его ип. Суть проблемы не открываются сайты которые добавлены в `Ruantiblock`. Другие сайты и локальные открываются, в роутер тоже входит. Не открываются именно добавленные для обхода в `Ruantiblock`. Подскажите как исправить
![2024-05-11_162017](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/10572914/d388ac4a-1d6b-47a1-b724-4d9454746206)

**Comment by gSpotx2f** [comment]
Не приходилось иметь дело с tailscale, никогда его не использовал. Owrt версия клиента tailscale, похоже, создаёт какие-то свои правила iptables для управления трафиком. Куда там что идёт и как - я без понятия. Может и возможно настроить, но, к сожалению, у меня нет времени этим заниматься...
