### ISSUE TITLE
[Feature request] Add user entries to the blacklist when edit done

### ISSUE THREAD

**Issue by Shkarlatov** [gSpotx2f/ruantiblock_openwrt#65]
Хотелось бы мгновенно применять пользовательские списки без обновления базовых.

Сейчас использую список `rublacklist`  + вношу новые домены в user list. Для применения нажимаю кнопку `Update blacklist`, это долго но еще при парсинге ловлю ошибку `ruantiblock: Error! Blacklist update error`  а следовательно и мои списки тоже не применяются.

Получается что у меня остаётся старая копия (`Safe blacklist update`) без моих новых доменов

**Comment by gSpotx2f** [comment]
>Хотелось бы мгновенно применять пользовательские списки без обновления базовых.

Мгновенно не получится. Во время обновления файл с записями пользователя (`user_entries`) разбирается встроенным парсером и записи, в зависимости от их типа, добавляются в конфиги nftables и dnsnasq. По сути, это та же процедура, что и для основного списка. Изначальная идея такая: базовые списки (полный реестр) регулярно обновляются автоматически по расписанию из заданного источника; записи пользователя - статичный список (дополнительные записи к реестру). Поэтому нет никакого смысла выносить записи пользователя в отдельную конфигурацию, они, по задумке, меняются редко, в отличии от базовых. Ваша проблема в ошибке обновления, её нужно решать.

>Сейчас использую список `rublacklist`

Не лучший выбор. На данный момент это самый огромный и ненадёжный источник блэклиста. Там просто гигантский json размером уже под 250мб, его парсить роутеру очень тяжело. К тому же бывают проблемы с доступностью и глюками API. Этот источник чисто на случай проблем с другими. Переключитесь на `zapret-info`.
