### ISSUE TITLE
чудесный глюк с генерацией списков

### ISSUE THREAD

**Issue by bonuzzz** [gSpotx2f/ruantiblock_openwrt#66]
Генерю списки удаленно Вашим парсером, далее автоматически подсовываются через Ваш плагин в днсмаск. Пара месяцев всё работало исправно, без нареканий. На днях добавил параметр, чтобы и запросы днс также шли через впн. До сего момента тоже работало. Сегодня сломались дны. Не запускается dnsmasq. В логе ошибка:
dnsmasq[1]: bad option at line 232791 of /tmp/dnsmasq.d/02-ruantiblock.dnsmasq
В самом файле строка:
sserver=/домен/10.110.11.1 
дальше ниже (разница в тысячу строк ):
nftsserver=/домен/10.110.11.1

Файл на 14 мегабайт. Остальные строки норм. В последующую итерацию файл также сгенерировался без косяков.
В чем прикол, понятия не имею.

upd: проглючила питоновская часть составления списка.

**Comment by gSpotx2f** [comment]
Интересно, не могу воспроизвести этот баг. Похоже какой-то сбой в момент записи в файл.
