### ISSUE TITLE
НЕ обновляется ruantiblock openwrt 23.05.3

### ISSUE THREAD

**Issue by nitro3188** [gSpotx2f/ruantiblock_openwrt#67]
добрый день! обновил openwrt 22.05 до 23.05 ради ruantiblock, но как не обновлялся blacklist, так и не обновляется.... нужна ваша помощь!
![2024-05-27_012124](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/162007146/11de617a-79fa-438a-9abc-6cffa0f9e2f2)

**Comment by nitro3188** [comment]
![2024-05-27_095815](https://github.com/gSpotx2f/ruantiblock_openwrt/assets/162007146/f8b431bb-ddc1-4885-9cb9-916a51105da4)
вот процесс установки из скрипта, вот на этом месте замирает, ждал час примерно

**Comment by gSpotx2f** [comment]
>добрый день! обновил openwrt 22.05 до 23.05 ради ruantiblock, но как не обновлялся blacklist, так и не обновляется.... нужна ваша помощь!

Проверьте доступен ли файл для скачивания на роутере:

    wget -O /tmp/01 "https://raw.githubusercontent.com/gSpotx2f/ruantiblock_blacklist/master/blacklist-1.1/fqdn/ruantiblock.dnsmasq"
    rm /tmp/01

>вот процесс установки из скрипта, вот на этом месте замирает, ждал час примерно

Попробуйте [установить без скрипта](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0), вручную скачав пакеты в /tmp. И лучше делать это в эмуляторе терминала (putty, если под windows), а не через вебморду.

**Comment by nitro3188** [comment]
спасибо, всё проделал по 10 раз - заработало!
