### ISSUE TITLE
Автоматическое получение списка подсетей по ASN?

### ISSUE THREAD

**Issue by flurmind** [gSpotx2f/ruantiblock_openwrt#68]
Здравствуйте. Давно пользуюсь, все хорошо работает, но не могу автоматизировать процесс получения подсетей, на примере instagram.com (по доменному имени он не работает).

Нашел скрипт для linux через whois.radb.net (добавляю в asn_hosts.txt: AS32934)
`#!/bin/sh

TEMP3="/tmp/tmp_asn_ip.lst"
RES3="/script/asn_ip.lst"
ASN="/script/asn_hosts.txt"

cat /dev/null > $TEMP3
cat /dev/null > $RES3

while read line || [ -n "$line" ]; do
	[ -z "$line" ] && continue
	[ "${line:0:1}" = "#" ] && continue
	whois -h whois.radb.net -- '-i origin '$line | grep ^route | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}' >> $TEMP3
done < $ASN

sort -t '.' -k1,1n -k2,2n -k3,3n $TEMP3 >> $RES3`

На выходе получаю файл с диапазоном IP, вставляю все в Записи пользователя и при обновлении - ошибка: ruantiblock: Error! Ipset wasn't updated.
[asn_ip.lst.txt](https://github.com/gSpotx2f/ruantiblock_openwrt/files/15471857/asn_ip.lst.txt)

Что интересно, вот сокращенный список подсетей  (человек собрал вручную с сайта 2ip.ru) и он работает:
[https://treeone.ru/diapazon-ip-adres-facebook-instagram-mikrotik/#page-content](url)

Прошу помочь разобраться, т.к. хотелось бы автоматизировать это дело, на случай смены каких-то IP у instagram.

**Comment by gSpotx2f** [comment]
>не могу автоматизировать процесс получения подсетей

Берите [отсюда](https://github.com/lord-alfred/ipranges/blob/main/facebook/ipv4_merged.txt) все суммированные подсети фейсбука сразу...

>На выходе получаю файл с диапазоном IP, вставляю все в Записи пользователя и при обновлении - ошибка: ruantiblock: Error! Ipset wasn't updated.

Возможно в списке присутствуют ip, которые уже есть в сете. Ipset не любит такого и при попытке добавить уже существующий ip в сет выдаёт ошибку. Всё что добавляется в записи пользователя исключительно на совести самого пользователя. Например, nftables в таких ситуациях ведёт себя более мягко и просто игнорирует повторный адрес не выбрасывая ошибку. Вообще, старая версия ruantiblock под iptables давным-давно устарела и больше не поддерживается.

**Comment by gSpotx2f** [comment]
>Т.к. добавил ссылку на https://github.com/lord-alfred/ipranges/blob/main/facebook/ipv4_merged.txt, но при обновлении не берет оттуда ничего.

Если открыть эту ссылку, то не трудно заметить, что она ведёт на веб-страницу гитхаба, а не на сам файл. URL файла выглядит так: https://raw.githubusercontent.com/lord-alfred/ipranges/main/facebook/ipv4_merged.txt (кнопка `Raw` сверху).

>Как правильно пользоваться?

Задать прямую ссылку на файл (без редиректов `30x` и пр.). Формат текстового файла должен соответствовать формату файла `user_entries`, который описан в [вики](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D0%B8-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F-%D0%B2-%D0%B1%D0%BB%D1%8D%D0%BA%D0%BB%D0%B8%D1%81%D1%82%D0%B5) и в вебморде ruantiblock. Также, кодировка вашего файла не должна быть сюрпризом для OpenWrt (лучше UTF-8 или ASCII) и символы окончания строки должны быть в unix-формате: `\n` (а не `\r\n` как в Windows). Ну и далее, как обычно, при обновлении блэклиста вместе с локальными записями пользователя будут добавляться и удалённые.

**Comment by flurmind** [comment]
Спасибо!
