### ISSUE TITLE
Траффик не ходит через wireguard

### ISSUE THREAD

**Issue by id259** [gSpotx2f/ruantiblock_openwrt#7]
Не могу заставить работать wireguard. Заблокированные сайты не трассируются.
```
root@OpenWrt:~# traceroute linkedin.com
traceroute to linkedin.com (13.107.42.14), 30 hops max, 38 byte packets
 1  *  *  *
 2  *  *  *
 3  *  *  *
 4  *  *  *
```

<details>
  <summary>/etc/config/network на роутере</summary>

```
config interface 'loopback'
        option device 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option packet_steering '1'
        option ula_prefix 'fd7b:4eb2:819c::/48'

config device
        option name 'br-lan'
        option type 'bridge'
        list ports 'lan1'
        list ports 'lan2'
        list ports 'lan3'
        list ports 'lan4'

config interface 'lan'
        option device 'br-lan'
        option proto 'static'
        option netmask '255.255.255.0'
        option ip6assign '60'
        option ipaddr '192.168.0.2'

config interface 'wan'
        option device 'wan'
        option proto 'dhcp'
        option peerdns '0'

config interface 'wan6'
        option device 'wan'
        option proto 'dhcpv6'
        option auto '0'
        option reqaddress 'try'
        option reqprefix 'auto'

config interface 'wg0'
        option private_key '<private_key>'
        list addresses '192.168.100.3/24'
        option listen_port '51820'
        option proto 'wireguard'

config wireguard_wg0
        option public_key '<publick_key>'
        option allowed_ips '0.0.0.0/0'
        option route_allowed_ips '0'
        option endpoint_host '94.228.122.230'
        option persistent_keepalive '25'
        option endpoint_port '51820'
```
</details>

<details>
  <summary>/etc/wireguard/wg0.conf на сервере</summary>

```
[Interface]
Address = 192.168.100.1
PrivateKey = <private_key>
ListenPort = 51820
PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ens3 -j MASQUERADE
[Peer]
PublicKey = <publick_key>
AllowedIPs = 192.168.100.3/24
```
</details>

В настройках ruantiblock в качетсве vpn-интерфейса указан wg0:

<details>
  <summary>Вкладка в настройках</summary>

![Screenshot 2022-08-12 at 18-22-54 OpenWrt - Settings - LuCI](https://user-images.githubusercontent.com/78232003/184389178-9abe33fa-b3e5-48d4-b9cf-cc93523e52ee.png)

</details>

Что ещё нужно сделать чтобы трафик начал ходить через wireguard?

**Comment by gSpotx2f** [comment]
Сам по себе тунель wireguard работает без ruantiblock? В настройках межсетевого экрана интерфейс `wg0` добавлен в зону `wan`?

**Comment by id259** [comment]
> интерфейс `wg0` добавлен в зону `wan`?

<details>
<summary>Вот таким образом?
</summary>

![Screenshot 2022-08-15 at 10-14-14 OpenWrt - General Settings - LuCI](https://user-images.githubusercontent.com/78232003/184592350-234a6738-65a2-4af7-bbad-763e2b474daa.png)

</details>

Во всяком случае после добавления зоны трафик начал ходить через вайгард.

**Comment by zalessky** [comment]
Та же проблема. Трафик не хочет ходить через wireguard

/etc/config/network на роутере:

`config interface 'wg0'
        option proto 'wireguard'
        option mtu '1420'
        option private_key 'private_key'
        list addresses '10.6.0.5/24'

config wireguard_wg0 'oracle'
        option public_key 'public_key'
        option preshared_key 'preshared_key'
        option persistent_keepalive '25'
        option endpoint_host 'IP'
        option endpoint_port '51820'
        list allowed_ips '0.0.0.0/0'
        option description 'Wireguard'
`

/etc/config/firewall на роутере:
`config zone
        option name 'wireguard'
        option forward 'REJECT'
        option output 'ACCEPT'
        option input 'REJECT'
        option masq '1'
        option mtu_fix '1'
        list network 'wg0'

config forwarding
        option dest 'wireguard'
        option src 'lan'

config forwarding
        option dest 'wan'
        option src 'lan'
`

Настройки как указано выше и в инструкции.  Прошу помощи. Что я сделал не так? Куда смотреть?
