### ISSUE TITLE
domain.*

### ISSUE THREAD

**Issue by tnkv** [gSpotx2f/ruantiblock_openwrt#70]
Есть возможность сделоать domain.* ???

Я хочу проксировать интел.ком что бы открывался нормально

intel.com
intel.de
onetrust.com 
cookielaw.org

.de открывается потому что у меня немецкий айпи как я понял, есть вариант более универсального способа?

**Comment by gSpotx2f** [comment]
>Есть возможность сделоать domain.* ???

Нет, домены в user_entries должны соответствовать правилам конфига dnsmasq, а он не поддерживает никаких подстановок, спецсимволов и пр. для записей доменов. Домены добавляются как есть по полному имени. Запись более высокого уровня включает в себя и все субдомены.
