### ISSUE TITLE
ТСПУ и DPI легко вычисляет openvpn.

### ISSUE THREAD

**Issue by koroleves** [gSpotx2f/ruantiblock_openwrt#71]
Добрый день, после всем известных событий запрещённым стал ещё один широко известный сайт.
Добавление его в список ручной фильтрации не помогает из-за dpi, который легко вычисляет openvpn( опробовал лично, видно , что день норм работает / день лежит (видно , что то включат фильтрацию, то нет)). Есть ли техническая возможность задействовать другие туннели, например AnyConnect или SoftEther?
Смотрел инструкции по этому сайту https://habr.com/ru/articles/415977/

**Comment by koroleves** [comment]
Есть подозрение, что я зря открыл топик и турель может быть любым, указывай интерфейс "tun0", "tun1" и т.д. в настройках

**Comment by gSpotx2f** [comment]
>Есть подозрение, что я зря открыл топик и турель может быть любым, указывай интерфейс "tun0", "tun1" и т.д. в настройках
Так и есть, интерфейс любого L3 VPN можно задать в настройках VPN-конфигурации.
