### ISSUE TITLE
опечатка

### ISSUE THREAD

**Issue by bonuzzz** [gSpotx2f/ruantiblock_openwrt#73]
<img width="249" alt="Screenshot 2024-08-07 at 17 16 49" src="https://github.com/user-attachments/assets/ce587d4c-8743-4123-8c6b-bc206c33508b">

**Comment by gSpotx2f** [comment]
[Исправил](https://github.com/gSpotx2f/ruantiblock_openwrt/commit/63cd8da0bbd2ba0cce73ab072af79518d88b98d5).
