### ISSUE TITLE
Работа с Amneziawg

### ISSUE THREAD

**Issue by uffemcev** [gSpotx2f/ruantiblock_openwrt#76]
Добрый день! Можно ли реализовать совместную работу ruantiblock и amneziawg?

**Comment by gSpotx2f** [comment]
>Добрый день! Можно ли реализовать совместную работу ruantiblock и amneziawg?

Думаю да, также как и с обычным WG, OpenVPN или любым L3 VPN.

**Comment by samara1532** [comment]
> Добрый день! Можно ли реализовать совместную работу ruantiblock и amneziawg?

проблема не совместную работу организовать, а организовать саму работу амнезии под врт.
судя по всему разработчики и не собираются этого делать, раз не чешутся столько времени.
выкинули какие-то исходники, собери сам.

BLACKTEMPLE SPACE обещают что-то запилить, но они много чего обещали.

**Comment by remittor** [comment]
@samara1532 

Вот инструкция для поднятия AWG на OpenWRT: https://4pda.to/forum/index.php?showtopic=1085698&view=findpost&p=131706716

Вот отсюда были взяты сорцы для сборки модулей AWG: https://github.com/lolo6oT/awg-openwrt

Как бы всё готово и настраивается через LuCI. И всё работает под руководством RuAntiBlock.

**Comment by samara1532** [comment]
@remittor 

круто, единое у меня появились проблемы с ютубом, с обычным wg не работает.
пока лень проверять что будет с awg.  подозреваю зря потрачу время.
ss пока работает, как заблочат подумаю о другом. может к тому времени запилят что получше по врт.
