### ISSUE TITLE
youtu.be

### ISSUE THREAD

**Issue by samara1532** [gSpotx2f/ruantiblock_openwrt#78]
проверял на рабочих, быстрых, частных, SS и WG  впн-ах. 
с другими ресурсами проблем нет.

если на ПК пускаю весь трафик через приложение впн, то всё ок.
в руантиблоке ставлю "включить режим полного прокси"  192.168.1.1/24
запускаешь стрим, секунд 10-30 проигрывает и встаёт. обновляешь страницу и всё по новой.
В записях видео рандомно себя ведет. иногда тоже самое, иногда воспроизводятся нормально.

изначально добавлял 
googlevideo.com
i.ytimg.com
yt3.ggpht.com

и все работало. теперь хоть весь гугл впихуй, не работает.
пробовал убрать и блеклисты, просто пустой пользователя. поставив опцию весь трафик в впн.

по итогу в настройке SS включил проксировать и UDP трафик и все заработало. с полным проксированием.
с частичным пришлось пихать куда больше чем выше. что-бы не зависало. (
впихнул  все что ниже, т.к. уже задолбался бетатестировать)

**так вот хотелось-бы узнать что на WG варианте нужно включить. что-бы так-же работало. 
или может я какой-то адрес пропускаю.** 

64.233.160.0/19
66.102.0.0/20
66.249.80.0/20
72.14.192.0/18
74.125.0.0/16
173.194.0.0/16
207.126.144.0/20
209.85.128.0/17
216.58.208.0/20
216.239.32.0/19
172.217.0.0/16

youtube.com
m.youtube.com
youtu.be
i.ytimg.com
yt3.ggpht.com
googlevideo.com

тут подборка всех адресов, если кому нужно.
https://github.com/touhidurrr/iplist-youtube/tree/main

**Comment by gSpotx2f** [comment]
Shadowsocks начали повально блокировать где-то на прошлой неделе, кажется. WireGuard, также, уже давно блокируют многие операторы связи. Что касается истории с youtube, то с 8 августа существенно ужесточили и расширили замедление/блокировку. В некоторых регионах youtube вообще не работает уже (включая сам сайт). Вообще, внереестровые (на ТСПУ) блокировки часто зависят от региона и конкретного провайдера. Поэтому то что заблокированно/замедленно у вашего провайдера можете выяснить только вы. В последний месяц блокировки постоянно меняются, если что-то работает сейчас, то это не значит, что будет работать завтра.

>так вот хотелось-бы узнать что на WG варианте нужно включить. что-бы так-же работало.
или может я какой-то адрес пропускаю.

Мне достаточно было добавить `googlevideo.com` в user_entries. У вашего провайдера, видимо, всё жёстче. Говорят можно ещё добавить `googleapis.com`, но это не точно.

**Comment by samara1532** [comment]
у нас пока не блочат ни один впн ("новые" территории)
проверю позже с googleapis.com
но плохо верю что поможет. т.к. помогло именно вкл. UDP трафика в настройках руантиблока на SS
хотелось-бы узнать что включить на WG т.к. он пока халявный, а за SS снимает денюшку. ютуб мотает трафик хорошо.

и в целом бы хотелось нубскую инструкцию по singbox + vless, пример конфига и что конкретно сделать что-бы руантиблок его видел.
пытался на нем пару раз подымать vless, но что-то не выходит. вроде и подключение есть, но нефига не работает.

**Comment by samara1532** [comment]
не прокатило с googleapis.com , пробовал добавить и все гугл айпи из ссылки выше.
пока не включишь "Отправлять в прозрачный прокси UDP-трафик"
секунд 30 воспроизводится и встаёт. 
на F12 весь вторичный трафик продолжает идти, просто перестают приходить пакеты с видео от googlevideo.com 
при этом как я писал, если видео уже запущено было с впн, то выключив UDP-трафик и обновив списки, оно и дальше воспроизводится. (перематывать не пробовал).
т.е. видимо ютуб вначале что-то пытается отправить, но не выходит или ему не нравится что udp приходят с др. адресом.


для понимания, без впн-а  вообще сайт толком не прогружается. все картинки, превью.
про видео не говорю.

единое что позитивного поменялось, вроде без айпи выше раньше не работало.
сегодня добавил googleapis.com и начало работать и без списка айпи. только домены.

**Comment by samara1532** [comment]
потыкался вроде нашел как поправить.

добавил в ip-filter адреса фришного wg
172.16.0.2/32
162.159.193.5/23

еще "Лимит IP адресов" 30" поставил вместо нуля, 
удалил ютуб из, "Домены 2-го уровня не подлежащие оптимизации"
но это помоему никак не влияло.

список адресов, не думаю что все нужны, но лень проверять.

googlevideo.com
youtube.com
youtu.be
m.youtube.com
ytimg.com
googleapis.com
ggpht.com
googleusercontent.com
yt.be
ytimg.l.google.com

**Comment by gSpotx2f** [comment]
Отключите ruantiblock, для исключения его влияния, и проверьте как доступны заблокированные сайты через wg на роутере (заверните весь трафик в wg). Пробуйте разные заблокированные сайты. Как я уже писал выше, wg сейчас лучше не использовать, ибо он блокируется. wg создавался максимально простым и быстрым, он не предполагает какой-либо маскировки или обфускации. Приложение VPN на ПК может использовать другой протокол или какие-то свои модификации, которые ТСПУ не распознаёт и пр.
