### ISSUE TITLE
Не могу настроить с L2TP

### ISSUE THREAD

**Issue by gizeasy** [gSpotx2f/ruantiblock_openwrt#79]
Здравствуйте. Сейчас скрипт работает в режиме tor, и все нормально))
Появилась необходимость использовать VPN, мне предоставили подключение по l2tp. Создал интерфейс он сразу выставился по умолчанию трафик пошел через l2TP. А теперь я не понимаю как перенаправить трафик который сейчас идет tor в l2tp.
В настройках скрипта нужно указать VPN интерфейс и прикол в том что там моего l2tp подключения. Подскажите пожалуйста как это все настроить.

**Comment by samara1532** [comment]
ну раз вы создали интерфейс, значит его название должно было появится в руантиблок, в разделе:
настройки - режим vpn - vpn интерфейс - xxx.L2TP.xxx
попробуйте на главной нажать нижнюю кнопку "выключение" службы руантиблок.
выбрать vpn интерфейс, потом в "основные" настройки - режим прокси - vpn 
применить настройки, и запустить службу, потом обновление блеклиста.

в интерфейсах, нажать на вашем l2tp изменить, и во второй вкладке снять галку с "Использовать шлюз по умолчанию"
(default gateway) . так-же сохранить и "Применить" главной кнопкой внизу .

**Comment by gizeasy** [comment]
Перезапуска ruantiblock, перезагружал роутер))) но интерфейс так и не появился в списках((
Там появляются только устройства

Интерфесы

![image](https://github.com/user-attachments/assets/6a64313a-1efb-4d5f-9fe3-6fdeb694dc57)


Устройсва

![image](https://github.com/user-attachments/assets/4384a7e4-0bc0-4efa-b115-b8ba7db543da)


ruantiblock / настройки vpn

![image](https://github.com/user-attachments/assets/ce56a8d8-df32-48a4-a63c-1f8b38e97178)

могу сбросить прошивку и с нуля все попробовать сделать, если конечно есть надежда что все исправится.

А авто настройку вашего скрипта нужно повторно проводить если хочу режим поменять?

**Comment by samara1532** [comment]
а он в руантиблоке и не появится, пока вы не запустите vpn интерфейс.
в списке только запущенные и работающие интерфейсы.
он у вас судя по скрину остановлен.

запустите его что-бы интерфейс работал, потом перезапустите руантиблок чтоб наверняка и в списке он появится.

**Comment by gizeasy** [comment]
Спасибо за ответы, еще раз все проверил, прописал все по рекомендациям, перезапустил и все завелось. Напишу еще скрипт чтоб после поднятия VPN обновлялся и перезапускался ruantiblock. Ну и проверка доступности сети, и вслучае не досупности переключение на tor. Tor уже имеет watchdog который ему мосты обновляет и перезапускает вслучае необходимости)))

Еще раз спасибо)) У меня просто openWRT всего неделю, раньше на padavan сидел.
