### ISSUE TITLE
Просьба добавить поддержку Shadowsocks и Xray

### ISSUE THREAD

**Issue by HedigehoG** [gSpotx2f/ruantiblock_openwrt#8]
Просьба добавить в выбор шлюзов другие сервисы как Shadowsocks и Xray
Описание с примером проброса https://manpages.org/ss-redir

**Comment by gSpotx2f** [comment]
Как я понял, по ссылке прозрачный прокси для shadowsocks (ss-redir). Там в примерах теже правила редиректа трафика в iptables что и для прозрачного прокси Tor. В Tor-конфигурации ruantiblock попробуйте задать номер порта прозрачного прокси, который соответствует локальному порту ss-redir (тот, что в параметре запуска `-l`).

**Comment by HedigehoG** [comment]
Думал об этом, но не помогло, ни смена порта в ruantiblock, ни в смене порта ss-local. Хотя при указании его в качестве Proxy SOCKS5 всё отрабатывает отлично. Не особо силён в *nix.

Но ознакомившись с темой, нашел более подходящее для меня решение основанное только на функционале Shadowsocks и правиле forward recentrst (TCP RST)
