### ISSUE TITLE
obfs4proxy RAM load 500%

### ISSUE THREAD

**Issue by nitro3188** [gSpotx2f/ruantiblock_openwrt#80]
Здравствуйте!
Роутер Xiaomi Ax3200  после старта (когда начинают обновляться базы) зависает через 5 минут просто наглухо... установлено Ruantiblock, HTTPS DNS Прокси, Adblock - раньше всё это работало без намёка на глюки, сейчас же пришлось отключить Adblock - хотя базы стоят щадящие - пока не виснет. Озу занято 211мб из 240мб (с отлюченным Adblock). В процессах вообще что-то страшное "2557 tor /usr/bin/obfs4proxy CPU 0% RAM
![2024-08-24_223705](https://github.com/user-attachments/assets/ce11554b-8e94-4659-8adf-704563d0d039)
![9](https://github.com/user-attachments/assets/2a9e352d-6f22-43b2-b2f8-c0f9abf58f74)
 501%"
Скрин приложил...

**Comment by gSpotx2f** [comment]
>В процессах вообще что-то страшное "2557 tor /usr/bin/obfs4proxy

Может утечка памяти, а может баг при отображении RAM (а может и то и другое). Sing-box, например, на некторых платформах тоже показывает нереальные цифры.
![01](https://github.com/user-attachments/assets/4b01f33e-3dae-43c2-914a-63f172e82cc1)
Смотрите через `free`, `top`. На скриншоте также видно, что tor использует четверть оперативки (возможно из-за tor-geoip, но не точно) - это ожидаемо. Dnsmasq прилично отъедает RAM, тоже ожидаемо (список доменов ruantiblock загружает dnsamsq). Tor требует оперативки, adblock требует оперативки для списков, ruantiblock требует оперативки для своих списков, которые ещё и растут каждый день. Всем нужна оперативная память. А у вас её не особо много. Возможно, придётся от чего-то отказаться или тонко оптимизировать настройки и списки. Покажите конфиг ruantiblock:

     cat /etc/config/ruantiblock

Для отладки можно запустить tor с выводом в консоль, посмотреть что пишет в процессе старта (как цепочки строит и пр.):

    /usr/sbin/tor -f /etc/tor/torrc

Запускайте из терминала, а не из веб-морды!

Про tor нужно помнить, что его блокируют весьма успешно (блокируют ноды по ip). Это не надёжный инструмент для обхода блокировок на роутере в режиме 24/365. На ПК можно держать в качестве варианта на случай ЧП, но необходимо постоянно проверять рабочие ноды.

**Comment by nitro3188** [comment]
> Покажите конфиг ruantiblock
``
config main 'config'
        option proxy_mode '1'
        option proxy_local_clients '1'
        option nftset_clear_sets '1'
        option allowed_hosts_mode '0'
        option bypass_mode '0'
        option enable_fproxy '0'
        option if_vpn 'tun0'
        option tor_trans_port '9040'
        option onion_dns_addr '127.0.0.1#9053'
        option t_proxy_port_tcp '1100'
        option t_proxy_port_udp '1100'
        option t_proxy_allow_udp '0'
        option enable_logging '1'
        option bllist_min_entries '3000'
        option bllist_ip_limit '0'
        option bllist_summarize_ip '1'
        option bllist_summarize_cidr '1'
        option bllist_ip_filter '0'
        option bllist_ip_filter_type '0'
        option bllist_sd_limit '16'
        list bllist_gr_excluded_sld 'livejournal.com'
        list bllist_gr_excluded_sld 'facebook.com'
        list bllist_gr_excluded_sld 'vk.com'
        list bllist_gr_excluded_sld 'blog.jp'
        list bllist_gr_excluded_sld 'msk.ru'
        list bllist_gr_excluded_sld 'net.ru'
        list bllist_gr_excluded_sld 'org.ru'
        list bllist_gr_excluded_sld 'net.ua'
        list bllist_gr_excluded_sld 'com.ua'
        list bllist_gr_excluded_sld 'org.ua'
        list bllist_gr_excluded_sld 'co.uk'
        list bllist_gr_excluded_sld 'amazonaws.com'
        list bllist_gr_excluded_sld 'spb.ru'
        list bllist_gr_excluded_sld 'appspot.com'
        list bllist_gr_excluded_sld 'googleusercontent.com'
        option bllist_fqdn_filter '1'
        option bllist_fqdn_filter_type '0'
        option bllist_enable_idn '0'
        option bllist_alt_nslookup '0'
        option bllist_alt_dns_addr '8.8.8.8'
        option update_at_startup '1'
        option enable_bllist_proxy '1'
        option vpn_route_check '0'
        option enable_tmp_downloads '1'
        option bllist_preset 'ruantiblock-fqdn'
        option add_user_entries '1'
``

> Запускайте из терминала, а не из веб-морды!

Putty:

``
root@OpenWrt:~# /usr/sbin/tor -f /etc/tor/torrc
Aug 25 22:02:31.813 [notice] Tor 0.4.8.10 running on Linux with Libevent 2.1.12-                                                                                                                                                             stable, OpenSSL 3.0.14, Zlib 1.2.13, Liblzma N/A, Libzstd N/A and Unknown N/A as                                                                                                                                                              libc.
Aug 25 22:02:31.813 [notice] Tor can't help you if you use it wrong! Learn how t                                                                                                                                                             o be safe at https://support.torproject.org/faq/staying-anonymous/
Aug 25 22:02:31.816 [notice] Read configuration file "/etc/tor/torrc".
Aug 25 22:02:31.824 [notice] You configured a non-loopback address '192.168.10.1                                                                                                                                                             :9040' for TransPort. This allows everybody on your local network to use your ma                                                                                                                                                             chine as a proxy. Make sure this is what you wanted.
Aug 25 22:02:31.835 [notice] You configured a non-loopback address '192.168.10.1                                                                                                                                                             :9040' for TransPort. This allows everybody on your local network to use your ma                                                                                                                                                             chine as a proxy. Make sure this is what you wanted.
Aug 25 22:02:31.835 [notice] Opening Socks listener on 127.0.0.1:9050
Aug 25 22:02:31.835 [warn] Could not bind to 127.0.0.1:9050: Address in use. Is                                                                                                                                                              Tor already running?
Aug 25 22:02:31.835 [notice] Opening DNS listener on 127.0.0.1:9053
Aug 25 22:02:31.835 [notice] Opened DNS listener connection (ready) on 127.0.0.1                                                                                                                                                             :9053
Aug 25 22:02:31.836 [notice] Opening Transparent pf/netfilter listener on 192.16                                                                                                                                                             8.10.1:9040
Aug 25 22:02:31.836 [warn] Could not bind to 192.168.10.1:9040: Address in use.                                                                                                                                                              Is Tor already running?
Aug 25 22:02:31.836 [notice] Opening Transparent pf/netfilter listener on 127.0.                                                                                                                                                             0.1:9040
Aug 25 22:02:31.836 [warn] Could not bind to 127.0.0.1:9040: Address in use. Is                                                                                                                                                              Tor already running?
Aug 25 22:02:31.836 [notice] Closing partially-constructed DNS listener connecti                                                                                                                                                             on (ready) on 127.0.0.1:9053
Aug 25 22:02:31.837 [warn] Failed to parse/validate config: Failed to bind one o                                                                                                                                                             f the listener ports.
Aug 25 22:02:31.837 [err] Reading config failed--see warnings above.
root@OpenWrt:~#
``

**Comment by nitro3188** [comment]
> посмотреть что пишет в процессе старта (как цепочки строит и пр.)

как вам мои цепочки? корректны?

**Comment by gSpotx2f** [comment]
>как вам мои цепочки? корректны?

Лог посмотрите внимательнее...

>Aug 25 22:02:31.836 [warn] Could not bind to 192.168.10.1:9040: Address in use. Is Tor already running?

Прежде чем запускать tor из консоли нужно остановить уже работающий экземпляр службы `service tor stop`.
И вообще, отладка tor выходит за рамки данного проекта.
