### ISSUE TITLE
Add GoodbyeDPI support for user list domains

### ISSUE THREAD

**Issue by VVi3ard** [gSpotx2f/ruantiblock_openwrt#81]
Thank you for the amazing software.

I have been using this utility for a long time and it works stably without failures.
However, recently in my country YouTube began to slow down via DPI, of course I added YouTube servers to the user list and the problem was solved. But still, my VPN was not designed for such large volumes of traffic that YouTube generates.

It would be great if for some domains it was possible not to use routing in VPN but to use fragmentation of dpi packets.

I tried to use your software together with Zapret (https://github.com/bol-van/zapret) but in the end everything stopped working for me. Perhaps I do not have enough qualifications to configure their simultaneous operation. However, even from the point of view of efficiency, it would be more convenient if it were within the framework of one program.

**Comment by gSpotx2f** [comment]
>However, even from the point of view of efficiency, it would be more convenient if it were within the framework of one program.

Two different projects, works differently. Unfortunately I have never used zapret and can't say anything about its configuration. I saw an opinion somewhere about successful use of ruantiblock together with zapret, but I don't know the details.
