### ISSUE TITLE
ss_set_server.sh shadowsocks on AmneziaVPN, OpenWRT

### ISSUE THREAD

**Issue by gegemon2012** [gSpotx2f/ruantiblock_openwrt#82]
Здравствуйте!
Краткая предыстория. 
Я специально разбираю тут самый простой для обывателя способ настройки и надеюсь что автор в будущем добавит проверенную опытным путем инструкцию по настройке протоколов поддерживаемых в AmneziaVPN.

Не краткая предыстория.
Решил приобрести VPS так как я считаю его необходимым и наиболее перспективным вариантом борьбы с государственной цензурой. Воспользовался вот этой инструкцией - https://pc-01.tech/outline-vpn-shadowsocks/ и настроил на сервере с помощью Outline Manager прокси shadowsocks. Используя вашу инструкцию "Использование бесплатных Shadowsocks прокси проекта Outline" я добавил прокси и настроил списки по "ruantiblock - fdqn". Но сайты из списка не открывались. Я попробовал запустить прокси на клиенте Outline но сайты из списка все равно не открывались. Я решил что Outline Manager не был правильно развернут на сервере и повторил процедуру установки Outline на сервере еще 2 раза, и оба они не помогли. Я стал искать альтернативу Outline Manager, и единственное что смог найти AmneziaVPN. С помощью нее я развернул на сервере протоколы "OpenVPN over SS", "OpenVPN over Cloak", "AmneziaWG", "XRay". Я понимаю что Xray универсальное и перспективное решение но не на все роутеры этот протокол влезает, а на старые вообще не влезает 8-10мб... Поэтому хотелось бы настроить подключение по "OpenVPN over SS", "OpenVPN over Cloak", "AmneziaWG"

Проблема:
В AmneziaVPN есть возможность получить настройки подключения по протоколам OpenVPN over SS" и "OpenVPN over Cloak" в виде shadowsocks но их не обрабатывает ваш скрипт ss_set_server.sh, при этом, через shadowsocks-libev через luci openwrt я спокойно импортирую данные настройки подключения но доступ к сайтам из списка не работает. Если импортировать данные настройки в Outline client то сайты из списка работают. Я понимаю что делаю что то не так. Хотелось бы понять что нужно еще настроить в luci чтобы работали подключения по вышеназванным протоколам.

П.С. Также у меня уже настроен https dns proxy (настройки по умолчанию) и "Перехват стороннего DNS трафика".
П.П.С Протокол AmneziaWG настраивал вот по этой инструкции https://github.com/itdoginfo/domain-routing-openwrt с помощью установки скрипта через putty: "sh <(wget -O - https://raw.githubusercontent.com/itdoginfo/domain-routing-openwrt/master/getdomains-install.sh)", но до конца еще не разобрался. Если указываю в rauntiblock в качестве vpn "awg0" то трафик через awg0 не идет вообще - смотрел через luci - overview - AmneziaWG.

**Comment by gSpotx2f** [comment]
>В AmneziaVPN есть возможность получить настройки подключения по протоколам OpenVPN over SS" и "OpenVPN over Cloak" в виде shadowsocks но их не обрабатывает ваш скрипт ss_set_server.sh, при этом, через shadowsocks-libev через luci openwrt я спокойно импортирую данные настройки подключения но доступ к сайтам из списка не работает.

Потому что [эти скрипты](https://github.com/gSpotx2f/ss_checker) для чистого shadowsocks (shadowsocks-libev в режиме прозрачного прокси). В любом случае, всё это уже не актуально. Shadowsocks-libev устарел и больше не развивается авторами, а сам протокол shadowsocks начали активно блокировать. И вообще, какой смысл инкапсулировать OpenVPN внутрь shadowsocks? OpenVPN сам по себе жирный и медленный (на слабых роутерах), а тут ещё и внутри другого туннеля. Задача же не в том чтобы именно OpenVPN поднять, а в обходе блокировок. Надо использовать самый простой и лёгкий из возможных вариантов, а не усложненять только потому, что есть какой-то готовый конфиг.

>Если импортировать данные настройки в Outline client то сайты из списка работают.

Outline в своём клиенте может модифицировать протокол для обфускации или противодействия блокировкам. Это не показатель. Имеет значение возможность работы в том клиенте который предполагается использовать, т.е. на роутере.

>П.С. Также у меня уже настроен https dns proxy (настройки по умолчанию) и "Перехват стороннего DNS трафика".

Сейчас https-dns-proxy сам умеет перехватывать сторонний DNS трафик, без дополнительных правил в firewall.

>П.П.С Протокол AmneziaWG настраивал вот по этой инструкции

Наверное логично вопросы по AmneziaWG задавать в том проекте откуда инструкция. Там уже есть какое-то своё решение со списком доменов, ruantiblock ставить не нужно. Вы, как-бы, установили один обход блокировок, а потом пытаетесь ещё один поднять параллельно. Понятно, что будут конфликты...

**Comment by gegemon2012** [comment]
> Потому что [эти скрипты](https://github.com/gSpotx2f/ss_checker) для чистого shadowsocks (shadowsocks-libev в режиме прозрачного прокси). В любом случае, всё это уже не актуально. Shadowsocks-libev устарел и больше не развивается авторами, а сам протокол shadowsocks начали активно блокировать. И вообще, какой смысл инкапсулировать OpenVPN внутрь shadowsocks? OpenVPN сам по себе жирный и медленный (на слабых роутерах), а тут ещё и внутри другого туннеля. Задача же не в том чтобы именно OpenVPN поднять, а в обходе блокировок. Надо использовать самый простой и лёгкий из возможных вариантов, а не усложненять только потому, что есть какой-то готовый конфиг.

А разве поднятие openvpn over SS на другом сервере через программу делающую все в автоматическом режиме это ли не "самый простой и лёгкий из возможных вариантов"? 
"Задача же не в том чтобы именно OpenVPN поднять, а в обходе блокировок" - так я ради этого тут и писал...
"Shadowsocks-libev устарел и больше не развивается авторами, а сам протокол shadowsocks начали активно блокировать." - в китае он до сих пор актуален, и чтобы избежать блокировок SS приходится использовать его внутри другого туннеля. А Xray разве не жирный и медленный на слабых роутерах? 
Так что мы имеем в итоге? Какой протокол вы предлагаете использовать из TOR, SS, OpenVPN, Xray для обхода блокировок?

**Comment by gSpotx2f** [comment]
>А разве поднятие openvpn over SS на другом сервере через программу делающую все в автоматическом режиме это ли не "самый простой и лёгкий из возможных вариантов"?

Насколько возможно простой и лёгкий для роутера, тот что не ест лишних ресурсов. Простоту/сложность установки обсуждать нет смысла, это субъективная категория.

>в китае он до сих пор актуален, и чтобы избежать блокировок SS приходится использовать его "поверх" другого туннеля.

Причём тут Китай? Погуглите на тему блокировок SS в РФ. Уровень блокировок зависит от провайдера, региона и х.з. от чего. Ситуация постоянно меняется. Есть провайдеры у которых и WG, и OpenVPN работают без проблем до сих пор, а есть такие где даже внутри РФ блочат VPN-протоколы. Что даст заворачивание OpenVPN в SS, если SS уже не работает (заблокирован)? Если же SS не заблокирован, то, опять же, зачем в него OpenVPN засовывать, почему не использовать на прямую как прокси для клиентов?

>А Xray разве не жирный и медленный на слабых роутерах?

Без понятия, не пользуюсь. Я тестировал vmess/vless в sing-box - меня устроила его производительность и размер для моего роутера.

>Так что мы имеем в итоге? Какой протокол вы предлагаете использовать из TOR, SS, OpenVPN, Xray для обхода блокировок?

Я не занимаюсь рекомендациями по выбору и настройке VPN/прокси, а также техподдержкой на расстоянии и пр. Если в общем, то прокси (в sing-box): vmess, vless. VPN: AmneziaWG, есть вариант обфусцированного OpenVPN (xor patch). Ruantiblock поддерживает L3 VPN (маршрутизация на интерфейс) или прозрачный прокси (редирект на локальный порт). Настраивается для разных VPN/прокси одинаково [п.5.2, п.5.3](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0).

**Comment by gegemon2012** [comment]
А есть какая -нибудь специфика найстроки AmneziaWG совместно с ruantiblock? Будет ли инструкция в вики?

**Comment by gSpotx2f** [comment]
>А есть какая -нибудь специфика найстроки AmneziaWG совместно с ruantiblock?

AmneziaWG тот же WG, со стороны ruantiblock никакой разницы. В самом AmneziaWG нужно отключить использование как шлюза по умолчанию и любое управление трафиком по спискам, которое там встроено.

>Будет ли инструкция на вики?

Инструкция для L3 VPN уже есть. Конкретно для AmneziaWG - нет, я не пишу инструкции по настройке VPN. К тому же, благодаря хайпу вокруг AmneziaWG, РКН обратил на него внимание, на прошлой неделе были сообщения что где-то в регионах у федералов начали блокировать. Это вопрос времени, AWG не имеет какой-то продвинутой обфускации. Допилят сигнатуры DPI на ТСПУ и AWG ждёт та же судьба, что и чистый WG. Как и любой другой протокол VPN/прокси про который начинают орать во все стороны и пиарить среди "непродвинутых масс" в статьях, инструкциях и на youtube.
