### ISSUE TITLE
Лишний символ в инструкции в Wiki

### ISSUE THREAD

**Issue by fildunsky** [gSpotx2f/ruantiblock_openwrt#83]
[В инструкции](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B0)

`uci set network.VPN.peerdns=0``
Лишний символ после 0

**Comment by gSpotx2f** [comment]
Спс, исправил
