### ISSUE TITLE
How to set proxy ip in transparent proxy mode?

### ISSUE THREAD

**Issue by Bazo0Z0o** [gSpotx2f/ruantiblock_openwrt#86]
Good day, I didn’t find in the configs, and in the documentation, how can I specify the proxy address in transparent proxy mode?
Thank you!

**Comment by gSpotx2f** [comment]
Transparent proxy must be running locally on the router (on the same host as ruantiblock). Nftables rules for redirecting traffic to transparent proxy [specify only the port](https://wiki.nftables.org/wiki-nftables/index.php/Performing_Network_Address_Translation_(NAT)#Redirect). The IP address is same to which client connections are accepted (gateway address).

**Comment by Bazo0Z0o** [comment]
But if i have transparent proxy somewhere else in the internet for example on aws vps

**Comment by gSpotx2f** [comment]
It doesn't work that way. Transparent proxy only works locally on the host. You can't use transparent proxy on another host. Ask Google about transparent proxies in Unix...

**Comment by Bazo0Z0o** [comment]
Did that already: only using VNP and local instance, thank you!
