### ISSUE TITLE
Исключить из правил маршрутизации

### ISSUE THREAD

**Issue by boozzze** [gSpotx2f/ruantiblock_openwrt#87]
Добрый день, столкнулся с необходимостью связать ruantiblock + pbr, чтобы ютуб, и еще некоторые сайты пустить через ru WARP

Проблема такого характера, если сайт есть в списке fdqn ruantiblock, но я хочу пустить его через pbr и warp , случается конфликт интересов, обход из списка (доступны напрямую) так же конфликтует, тк так или иначе записывает что-то в dnsmasq, а есть ли способ указать домены, которые вообще не будет трогать при построении маршрутизации? 

Например, чтобы проверить, что warp через pbr завёлся, я вписал whoer.com, но он уже был промаршрутизирован ruantiblock'ом (исключить из обхода bypass_entries тоже пробовал)

Я не упёрся в конкретный проверяльщик ипа, я могу прописать 2ip.ru , но есть другие планы на такую маршрутизацию, где еще будут встречаться конфликты, которые хочется понять, Как решить 🙌

Ютуб завёлся, то есть дикого конфликта у них нет, только из-за пересечения списков.

**Comment by boozzze** [comment]
Или может у вас планируется возможность пробрасывать в несколько интерфейсов несколько списков?
Щас вот дискорд отьехал, тоже можно бы через варп пробросить, как и ютуб

Или уже можно на уровне конфига как-то реализвать без luci такой проброс?

**Comment by gSpotx2f** [comment]
>Проблема такого характера, если сайт есть в списке fdqn ruantiblock, но я хочу пустить его через pbr и warp , случается конфликт интересов, обход из списка (доступны напрямую) так же конфликтует, тк так или иначе записывает что-то в dnsmasq, а есть ли способ указать домены, которые вообще не будет трогать при построении маршрутизации?

Способ есть - фильтр доменов в модуле-парсере (fqdn_filter), он удаляет домены по шаблонам из реестра. Для этого нужно [установить модуль-парсер](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/Lua%E2%80%91%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C) и формировать блэклист (конфиги nft и dnsmasq) на роутере. Режим блэклиста по умолчанию (`ruantiblock-fqdn`, `ruantiblock-ip`) просто скачивает при обновлении уже готовые конфиги [с github](https://github.com/gSpotx2f/ruantiblock_blacklist), это мой список с теми фильтрами и дополнительными записями, которые мне видятся оптимальными. Вы можете формировать свой список, который удобен для вас. Либо на роутере установив парсер, либо как и в указанном выше репо на github изменив конфиг парсера для вашего списка (нужно форкнуть [репозиторий](https://github.com/gSpotx2f/ruantiblock_blacklist), а на роутере в ruantiblock изменить URL к файлам из вашего репо - имя аккаунта github в ссылках `gSpotx2f` на `boozzze`).

>Или может у вас планируется возможность пробрасывать в несколько интерфейсов несколько списков? В идеале не лимитировать количество списков и интерфейсов, хоть 5 списков в 5 интерфейсов (это может быть как список в ручную введенный, так и ссылка на лист, как и то и то вместе)

Фактически, это дублирование PBR. PBR уже умеет всё это делать. Ruantiblock и PBR, в общем, работают по одному принципу, разница в назначении. PBR - универсальное решение, масштабируемое для сложных конфигураций с разным количеством интерфейсов, прокси и т.п. Ruantiblock, наоборот, узкоспециализированное решение для одной конкретной задачи - обход блокировок в РФ по реестру. Как-бы нет особого смысла повторять функциональность PBR. Можно использовать их совместно, а пересечение списков контролировать с помощью фильтров ruantiblock при формировании блэклиста.

**Comment by boozzze** [comment]
> Фактически, это дублирование PBR. PBR уже умеет всё это делать. Ruantiblock и PBR, в общем, работают по одному принципу, разница в назначении. PBR - универсальное решение, масштабируемое для сложных конфигураций с разным количеством интерфейсов, прокси и т.п. Ruantiblock, наоборот, узкоспециализированное решение для одной конкретной задачи - обход блокировок в РФ по реестру. Как-бы нет особого смысла повторять функциональность PBR. Можно использовать их совместно, а пересечение списков контролировать с помощью фильтров ruantiblock при формировании блэклиста.

Но pbr нестабильный (ранимый, требует рестарты ребуты) +  сложновато подружить с ruantiblock из-за описанной проблемы выше , и прочитанного вашего решения )
Мне кажется, оч полезно и востребовано будет то, что я предложил, грубо говоря, чтобы не перегружать интерфейс luci, в отдельную вкладку это вынести всё, и всё останется как есть, но очень расширится функционал

Ведь в случае с блокировками работает фраза "дальше - больше", и вот - позавчера инст, вчера ютуб, сёдня дискорд, завтра вацап и тд

И пробросить такие вещи через Warp будет классной возможностью минимально потерять в пинге для связи, продолжить пользоваться своим регионом, без рекламы для ютуб

**Comment by fizsef** [comment]
Поддерживаю, автора поста. Очень не хватает функции назначения списка конкретному интерфейсу. 
Ну или хотя бы, чтобы добавленный в исключения  домен полностью исключался из правил. А то у меня домен 4pda.to есть в списке руантиблок, список беру с гит, не свой, соответственно править его я не могу, а мне этот домен нужно направить в другой туннель, не туда же куда весь список, а в туннель с зарубежным айпи через PBR. Ну, как выше уже товарищ сказал, не работает правило в PBR для домена, если он уже есть в списке для рунатиблок.

**Comment by boozzze** [comment]
Пока мы тут рассуждаем, по-немногу тестриую pbr + ruantiblock, и вот какая ситуация. Касается ребенка
для игры в BrawlStars поднят днс, который без впн даёт играть. проверено не единожды. Без pbr полёт отличный
```

Список хостов, которые исключаются из обхода блокировок (всегда доступны напрямую)
#brawl
brawlstarsgame.com dns.nullsproxy.com
game.brawlstarsgame.com dns.nullsproxy.com
cdn.id.supercell.com dns.nullsproxy.com
```

вот так вот без pbr работало. в pbr прописал только 2ip.ru и ютубы через WARP, теперь вышеупомянутый brawl не видит, что ему прописан правильный ДНС для работы из РФ без впн.

Как это может быть связано ? Лист обхода руантиблок и запущенный pbr

**Comment by boozzze** [comment]
прописал этот dns через stubby, игра заработала,
youtube и discord завернул через pbr в warp.

почти всегда после ребута всё  заводится, процентов 60 успешных ребтов

оч хотелось бы от вас фулл версию с тем уровнем самым уровнем стабильности

**Comment by gSpotx2f** [comment]
В последней версии добавил [экземпляры записей пользователя](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D0%B8-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F-%D0%B2-%D0%B1%D0%BB%D1%8D%D0%BA%D0%BB%D0%B8%D1%81%D1%82%D0%B5) с разными настройками прокси/VPN.
![](https://github.com/gSpotx2f/ruantiblock_openwrt/blob/master/screenshots/05.jpg?raw=true)
