### ISSUE TITLE
Перенаправление всей доменной зоны

### ISSUE THREAD

**Issue by 00enterausername00** [gSpotx2f/ruantiblock_openwrt#88]
Собственно все работает отлично, но хочется доменную зону одной страны целиком завернуть в тоннель. Через user_entries не получилось. Можно как-то этого добиться?
Спасибо за софтину!

**Comment by gSpotx2f** [comment]
>Собственно все работает отлично, но хочется доменную зону одной страны целиком завернуть в тоннель. Через user_entries не получилось. Можно как-то этого добиться?

Добавить в user_entries домен первого уровня, например `ru`. Запись верхнего уровня охватывает все субдомены нижних уровней. Это правило конфигурации dnsmasq.

**Comment by 00enterausername00** [comment]
Так я пробовал - не работает. При выполнении /usr/bin/ruantiblock update после добавления, даже значение  FQDN не меняется. Пробовал еще с точкой перед доменом и со звездочкой и точкой. Перезагружать после добавления тоже пробовал

**Comment by gSpotx2f** [comment]
Посмотрел код, там строгий шаблон для отбора доменов. Запись типа `ru` он не понимает как FQDN (`xxx.xxx`) и игнорирует как мусор не совпадающий с шаблоном. Изначально не предполагал добавления доменов первого уровня в user_entries. Попробуйте [этот](https://gist.github.com/gSpotx2f/4762056bc1e3e33a169728abab3e9b74) файл, в нём изменён шаблон FQDN. Замените им `/usr/bin/ruantblock`.

**Comment by 00enterausername00** [comment]
С этим файлом работает, спасибо
