### ISSUE TITLE
Sing-box TProxy

### ISSUE THREAD

**Issue by deathspank666** [gSpotx2f/ruantiblock_openwrt#89]
Не удается настроить работу ruantiblock с sing-box в режиме trpoxy.
В настройках ruantiblock указывается режим прозрачного прокси, в настройках sing-box прописывается "inbounds":
```
    {
      "tag": "tproxy-in",
      "type": "tproxy",
      "listen": "127.0.0.1",
      "listen_port": 1100,
      "tcp_fast_open": true,
      "udp_fragment": true,
      "sniff": true,
      "domain_strategy": "prefer_ipv4"
    }
```
В tun режим sing-box сам по себе медленный, а сейчас возникла необходимость гнать большие объемы трафика из-за блокировок youtube и discord (возможно еще стриминговые сервисы в будущем).
Поддержка успешна trpoxy реализована в https://github.com/itdoginfo/podkop , но проект только создался и под сомнением создания функционал, присутствующий в ruantiblock (например подгружаемые пользовательские списки, у автора свое видение на этот счет).
Буду признателен за советы по настройке или любые другие рекомендации.

**Comment by gSpotx2f** [comment]
Режим прозрачного прокси в ruantiblock применяет действие `redirect` в правилах nftables. Для sing-box нужно правило с действием `tproxy` (и ещё прописать маршрутизацию для локальных пакетов). Изначально режим прозрачного прокси (правила nftables) создавался для tor (а также shadowsock-libev, redsocks и пр.), ему нужен именно `redirect`. Про проблему с sing-box я в курсе, просто раньше все использовали режим tun и не было необходимости заморачиваться с TProxy... Добавлю поддержку `tproxy` в следующей версии ruabtiblock.

Кстати, `"listen": "127.0.0.1",` будет принимать только трафик исходящий от самого роутера.

**Comment by gSpotx2f** [comment]
Добавил [поддержку tproxy](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-ruantiblock-%D0%B4%D0%BB%D1%8F-%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%BD%D0%BE%D0%B9-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D0%BF%D1%80%D0%BE%D0%BA%D1%81%D0%B8-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%BE%D0%BC-sing%E2%80%91box#31-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D1%8F-sing-box-%D1%81-%D0%BF%D1%80%D0%BE%D0%B7%D1%80%D0%B0%D1%87%D0%BD%D1%8B%D0%BC-%D0%BF%D1%80%D0%BE%D0%BA%D1%81%D0%B8-tproxy) в новой версии.

**Comment by deathspank666** [comment]
Спасибо, sing-box через tproxy работает отлично!
