### ISSUE TITLE
Не хочет нормально работать Twitter

### ISSUE THREAD

**Issue by ilyasyakubov** [gSpotx2f/ruantiblock_openwrt#9]
Здравствуйте!

Железка `Nanopi r5s (4GB)` + фирменная прошивка `FriendlyWRT` на основе `OpenWRT 21.02` + `Wireguard VPN`.
Настроил `ruantiblock` по инструкции. Завелось с пол тычка. Модуль парсер `ruab_parser.py`, список `ruantiblock.fkdn`.

Все сайты открываются нормально, кроме `twitter.com`. С ним беда. То изображения пропадают, то внешние ссылки `t.co` не открываются. При прямом соединении с `Wireguard VPN` сайт работает нормально. Если выбрать список `antifilter`, то сайт более или менее работает. В чем может быть дело?

**Comment by gSpotx2f** [comment]
Включите `Записи пользователя`, добавьте в список записей домен `twimg.com` и обновите блэклист. Либо в вебморде, либо из консоли:

    echo "twimg.com" >> /etc/ruantiblock/user_entries
    uci set ruantiblock.config.add_user_entries='1'
    uci commit ruantiblock
    /usr/bin/ruantiblock update

**Comment by ilyasyakubov** [comment]
> Включите `Записи пользователя`, добавьте в список записей домен `twimg.com` и обновите блэклист. Либо в вебморде, либо из консоли:
> 
> ```
> echo "twimg.com" >> /etc/ruantiblock/user_entries
> uci set ruantiblock.config.add_user_entries='1'
> uci commit ruantiblock
> /usr/bin/ruantiblock update
> ```

Спасибо за оперативный ответ! Я правильно понимаю, то, что вы предлагаете, поможет с отображением картинок? А что делать с ссылками на внешние сайты типа ‘t.co?’ Тоже добавить в user_entries?

**Comment by ilyasyakubov** [comment]
Спасибо, помогло!
