### ISSUE TITLE
Последний снапшот

### ISSUE THREAD

**Issue by Alexey71** [gSpotx2f/ruantiblock_openwrt#91]
Здравствуйте. Перестало добавлять адреса которые прописаны в "Записи пользователя", режим работы  "Только записи пользователя. Стало так на последних снапшотах openwrt
[ruantiblock-1.log](https://github.com/user-attachments/files/17530295/ruantiblock-1.log)

**Comment by gSpotx2f** [comment]
В последних снэпшотах изменили имя папки `/tmp/dnsmasq.d`, теперь оно создаётся динамически для каждого экземпляра. Нужно будет что-то решать с этим.  Как временное решение можно исправить init файл dnsmasq
`/etc/init.d/dnsmasq`:
Строку 1149

    config_get dnsmasqconfdir "$cfg" confdir "/tmp/dnsmasq${cfg:+.$cfg}.d"

нужно заменить на

    config_get dnsmasqconfdir "$cfg" confdir "/tmp/dnsmasq.d"

Или замените весь файл `/etc/init.d/dnsmasq` [этим](https://gist.github.com/gSpotx2f/186c0a1ad99bfa6afa166d2ffecfd30f).
Вообще, snapshot - тестовая ветка для разработчиков, там могут быть баги или существенные изменения ломающие существующие приложения. Я могу гарантировать работу только на стабильной ветке.

**Comment by gSpotx2f** [comment]
Добавил возможность выбора папки экземпляра dnsmasq (в модальном окне полного выключения на странице службы). При первом запуске ruantiblock init-скрипт сам найдёт папку экземпляра dnsmasq в `/tmp`. Если в системе один экземпляр dnsmasq (по дефолту и в большинстве конфигураций), то больше никаких настроек не требуется. Перед установкой новой версии 2.1 старую нужно [полностью удалить](https://github.com/gSpotx2f/ruantiblock_openwrt/wiki/%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-ruantiblock), конфиги не совместимы!
