### ISSUE TITLE
Балансировка между интерфейсами

### ISSUE THREAD

**Issue by mglants** [gSpotx2f/ruantiblock_openwrt#92]
Добрый день, спасибо за отличный проект. Собственно вопрос следующий, у меня несколько провайдеров и на каждом провайдере по своему vpn интерфейсу отправленных в разные хостеры - вопрос может ли как-то ruantiblock балансить между интерфейсами как это делает mwan3

**Comment by gSpotx2f** [comment]
Нет не может. Задача этого проекта - обход блокировок по блэклисту. Балансировка и резирвирование, это вообще другая область.
