### ISSUE TITLE
Добавить локальный DNS сервер.

### ISSUE THREAD

**Issue by EikeiDev** [gSpotx2f/ruantiblock_openwrt#93]
Есть ли возможность добавить локальный DNS сервер? (в следующем обновлении плагина).
как это использует например SSClash (OpenClash), на отдельном порту светится локальный DNS, а в конфирурации настраиваются upsteam и boostrap сервера. Просто отпала бы необходимость ставить что то по типу https-dns-proxy и прочее)

**Comment by gSpotx2f** [comment]
То что вы описали - это dnsmasq, стандарный DNS-сервер (резолвер) OpenWrt. Зачем ещё один? В чём будет заключаться его роль? Прелесть https-dns-proxy в том, что он специально написан для dnsmasq и замечательно с ним работает. Объясните развёрнуто, в чём проблема текущей схемы c https-dns-proxy. Про OpenClash и пр. я не в курсе, это что-то китайское для обхода тамошних блокировок?
