### ISSUE TITLE
В автоинсталяции старая версия интерфейса

### ISSUE THREAD

**Issue by Wiedzmin89** [gSpotx2f/ruantiblock_openwrt#96]
на чистую openwrt установил проект командой: `wget --no-check-certificate -O /tmp/autoinstall.sh https://raw.githubusercontent.com/gSpotx2f/ruantiblock_openwrt/master/autoinstall/2.x/autoinstall.sh && chmod +x /tmp/autoinstall.sh && /tmp/autoinstall.sh`

по файловой структуре - новый фомат
![image](https://github.com/user-attachments/assets/e9fbf8a8-1101-41c4-9bcf-56430b0f249c)

а интерфейс старого формата
![image](https://github.com/user-attachments/assets/d0cb5325-c10a-4d51-8558-3191e0bd8f30)

**Comment by HentayHentay** [comment]
Проблема была такая
Кеш сбрось браузера
