### ISSUE TITLE
Проект не работает с dnscrypt-proxy

### ISSUE THREAD

**Issue by Wiedzmin89** [gSpotx2f/ruantiblock_openwrt#97]
Заметил, что установщик теперь предлагает установить https-dns-proxy, без него ruantiblock не функционирует корректно: блокировки не обходятся.

Обычно я использовал dnscrypt-proxy с настроенным ODoH, существует ещё несколько провайдеров DoH для openwrt, вы решили от них отказаться в пользу https-dns-proxy?

**Comment by gSpotx2f** [comment]
>Заметил, что установщик теперь предлагает установить https-dns-proxy, без него ruantiblock не функционирует корректно: блокировки не обходятся.

Так и есть, провайдеры спуфят не шифрованный DNS подменяя адреса заблокированных сайтов. В вики и раньше была рекомендация установить https-dns-proxy. В скрипт установки добавил, потому что многие юзеры пропускают этот шаг с шифрованием DNS.

>вы решили от них отказаться в пользу https-dns-proxy?

Собственно, всё осталось как и раньше. Главное, чтобы dnsmasq работал в роли DNS-сервера для локальной сети, а куда перенаправлять запросы для шифрования DNS можете выбирать сами. https-dns-proxy был написан специально для dnsmasq и в OpenWrt устанавливается и настраивается без лишних усилий, поэтому логично его рекомендовать в первую очередь.
