### ISSUE TITLE
Не работает режим полного проксирования

### ISSUE THREAD

**Issue by Wiedzmin89** [gSpotx2f/ruantiblock_openwrt#98]
После обновления не работает fullproxy mode - проверил и через blacklist settings и через user list

**Comment by konstantisu** [comment]
Да, тоже какие-то странности... Пользуюсь только юзерлистом, без загрузки "чужих", так при установке начисто долго удивлялся, почему юзерлист вдруг тут же "самоочищается" после сохранения. Какой-то глюк, в  закладке "Настройки блеклиста" остается поле для заполнения своих доменов, как было раньше. На чем я и погорел... Поле исчезает только после "передергивания" с загрузуи чужих листов на "только пользовательские". А вот с "полным прокси" тоже похожая история, похоже... Аж заколдобило, так все перекосило, трафик DNS попер в туннель, и там скончался закономерно... В общем, странно стало, на версиях меньше 2.х все было ок :)

**Comment by gSpotx2f** [comment]
@konstantisu, https://github.com/gSpotx2f/ruantiblock_openwrt/issues/100#issuecomment-2481258799. Вообще, принято создавать новые тикеты для разных проблем, иначе получается бардак.
