### ISSUE TITLE
Инсталлятор портит конфиг dhcp

### ISSUE THREAD

**Issue by TyroSpy** [gSpotx2f/ruantiblock_openwrt#99]
Если уж вмешиваться в конфиги пользователя, то делать это не затрагивая его параметры, правильно будет так:
```
uci add_list dhcp.@dnsmasq[0].rebind_domain='onion'
uci commit dhcp
```

**Comment by gSpotx2f** [comment]
Да, надо исправить. Пора вообще выпилить прозрачный доступ в onion, это опасно.
